# Generated by /feature-spec
# Feature: Build Queue Dispatch to Forge (FEAT-JARVIS-005)
# Stack: python
# Assumptions: 11 (see feat-jarvis-005-build-queue-dispatch-to-forge_assumptions.yaml)
# Generated: 2026-04-29T15:00:00Z

@feat-jarvis-005 @forge-feedback @fleet-dispatch
Feature: Build Queue Dispatch to Forge
  As Jarvis
  I want to publish build-queue requests to Forge as a real JetStream
  message, listen for the matching stage-complete events, and surface
  them back to the originating session between prompts
  So that Rich can hand off a planned feature to Forge from the chat
  loop and watch its progress arrive on the next prompt cycle, with a
  trace-rich history of what was queued and what happened to it,
  without ever blocking the supervisor's next turn

  Background:
    Given Jarvis is running with a connected NATS transport
    And Jarvis has subscribed to Forge's pipeline stage-complete events
    And Rich is in an active terminal chat session

  # ─── GROUP A: Key Examples ──────────────────────────────────────────────

  # Why: Phase 3 close criterion #5 — the real publish replaces the Phase 2 stub
  @task:TASK-J005-005
  @key-example @smoke
  Scenario: Queueing a build publishes the request to Forge and returns a queued acknowledgement
    Given a planned feature with a valid feature identifier, repository, and feature-yaml path
    When Rich asks Jarvis to queue the build
    Then Forge should receive the build-queued request on the singular per-feature subject
    And the published request should identify Jarvis as the trigger
    And the published request should record the originating adapter as the active session's adapter
    And the supervisor should be told the build was queued
    And the acknowledgement should carry the correlation identifier, the feature identifier, the queued timestamp, and the publish target

  # Why: Phase 3 close criterion #6 — stage-complete events route back to the originating session
  @task:TASK-J005-003
  @key-example @smoke
  Scenario: A stage-complete event for a queued build surfaces on the originating session
    Given Rich has queued a build from this session
    And Forge is processing that build
    When Forge announces that a stage of the build has completed
    Then a notification should be queued for delivery on Rich's session
    And no notification should be queued for any other session

  # Why: DDR-029 — append-only edges preserve the audit trail
  @task:TASK-J005-004
  @key-example @smoke
  Scenario: A stage-complete event is recorded as an append-only edge on the originating routing history entry
    Given Rich has queued a build from this session
    And the build's queue-time routing history entry has been written
    When Forge announces that a stage of the build has completed
    Then a stage-complete edge should be appended to that routing history entry
    And the originating routing history entry should remain unchanged

  # Why: DDR-029 — multiple stages do not collide; each one becomes a distinct edge
  @task:TASK-J005-004
  @key-example
  Scenario: Multiple stage-complete events for one build produce multiple distinct stage-complete edges
    Given Rich has queued a build from this session
    When Forge announces that three stages of the build have completed in sequence
    Then three distinct stage-complete edges should be recorded against the originating routing history entry
    And no earlier stage-complete record should be overwritten by a later one

  # Why: DDR-030 — notifications render between prompts only, in the canonical cross-adapter shape
  # [ASSUMPTION: confidence=high] CLI line format is "[HH:MM] Forge {feature_id}: stage {stage_label} ({status})" per DM-forge-notification §1
  @task:TASK-J005-007
  @key-example @smoke
  Scenario: Pending notifications are rendered to the CLI before the next prompt is read
    Given a stage-complete notification for Rich's session is pending delivery
    When the chat loop is ready to read Rich's next input
    Then Rich should see one line for that notification before the next prompt
    And the line should show the local time, the feature identifier, the stage label, and the stage status
    And the pending notification queue should be empty after the line is rendered

  # Why: First live forge_build_queue trace — feeds the v1.5 learning substrate
  @task:TASK-J005-005
  @key-example
  Scenario: Queueing a build writes a forge_build_queue routing history entry without blocking the supervisor
    Given a planned feature ready to be queued
    When Rich asks Jarvis to queue the build
    Then a routing history entry should be written for that build
    And the entry should be tagged as a forge build-queue dispatch
    And the entry should carry the correlation identifier as its subagent task identifier
    And the entry should record the originating session, the originating adapter, and the publish target
    And the supervisor should not have waited for the routing history write to land

  # ─── GROUP B: Boundary Conditions ───────────────────────────────────────

  # Why: Just-inside boundary — the per-session queue absorbs a full burst without loss
  # [ASSUMPTION: confidence=high] DDR-030 — default per-session cap is 100 entries
  @task:TASK-J005-006
  @boundary
  Scenario: The per-session notification queue holds the full configured number of pending notifications
    Given the per-session notification cap is one hundred
    When one hundred stage-complete notifications are enqueued for Rich's session
    Then all one hundred notifications should be available on the next prompt cycle
    And they should be rendered in the order Forge published them

  # Why: Just-outside boundary — the (cap + 1)th eviction is observable
  # [ASSUMPTION: confidence=high] DDR-030 — eviction policy is oldest-first FIFO
  @task:TASK-J005-006
  @boundary @negative
  Scenario: Enqueueing one notification beyond the per-session cap evicts the oldest entry
    Given the per-session notification queue is full at the configured cap
    When one more stage-complete notification is enqueued for that session
    Then the oldest pending notification should be discarded
    And the queue length should remain at the configured cap
    And an overflow warning should be recorded for the discarded notification

  # Why: Just-inside boundary — the correlation map absorbs the full configured number of in-flight builds
  # [ASSUMPTION: confidence=high] DDR-028 — default correlation map cap is 1000 entries
  @task:TASK-J005-003
  @boundary
  Scenario: The correlation map holds the full configured number of in-flight build correlations
    Given the correlation map cap is the configured value
    When that many builds have been queued without their correlations being evicted
    Then every queued correlation should still be resolvable for incoming stage-complete events

  # Why: Just-outside boundary — the (cap + 1)th correlation evicts the oldest
  # [ASSUMPTION: confidence=high] DDR-028 — eviction policy is LRU oldest
  @task:TASK-J005-003
  @boundary @negative
  Scenario: Registering one correlation beyond the configured cap evicts the oldest correlation
    Given the correlation map is full at the configured cap
    When one more build is queued and its correlation is registered
    Then the oldest correlation should be removed from the map
    And an eviction warning should be recorded for the removed correlation
    And a stage-complete event arriving for the evicted correlation should be silently dropped

  # Why: Just-inside boundary — a publish that lands under the timeout returns "queued"
  # [ASSUMPTION: confidence=high] DDR-025 — default publish timeout is 5 seconds
  @task:TASK-J005-005
  @boundary
  Scenario: A publish acknowledgement received within the configured timeout returns a queued acknowledgement
    Given the publish timeout is set to its configured default
    When the broker acknowledges the publish before the timeout elapses
    Then the supervisor should be told the build was queued
    And the queued acknowledgement should reference the message stored in the pipeline stream

  # Why: Just-outside boundary — a publish that misses the timeout reports transport unavailable
  @task:TASK-J005-005
  @boundary @negative
  Scenario: A publish that does not acknowledge within the configured timeout reports the transport as unavailable
    Given the publish timeout is set to its configured default
    When the broker fails to acknowledge the publish before the timeout elapses
    Then the supervisor should receive a degraded response indicating the JetStream publish failed
    And a routing history entry should still be written recording the transport-unavailable outcome
    And no correlation should be registered for the un-published build

  # ─── GROUP C: Negative Cases ────────────────────────────────────────────

  # Why: Audit-trail invariant — only Forge may publish stage-complete events Jarvis acts on
  # [ASSUMPTION: confidence=high] Subscriber drops with WARN unless envelope source_id == "forge" per API-events §3
  @task:TASK-J005-003
  @negative
  Scenario: A stage-complete event from an unrecognised source is dropped without surfacing
    Given Rich has queued a build from this session
    When a stage-complete event arrives for that build but it claims a non-Forge source
    Then no notification should be queued for any session
    And no stage-complete edge should be recorded against the originating routing history entry
    And the unexpected source should be reported in the operator log

  # Why: Without a registered correlation there is no session to surface the event to
  # [ASSUMPTION: confidence=high] Subscriber auto-acks and drops silently on unknown correlation per DDR-027 + design §8
  @task:TASK-J005-003
  @negative
  Scenario: A stage-complete event for an unknown correlation is silently dropped
    Given the correlation map has no entry for an incoming event's correlation identifier
    When that stage-complete event is delivered to the subscriber
    Then no notification should be queued for any session
    And no stage-complete edge should be recorded
    And no error should be raised on the subscriber

  # Why: DDR-021 inheritance — NATS-down must soft-fail visibly to the reasoning model
  @task:TASK-J005-009
  @negative
  Scenario: Queueing a build when the NATS transport is unavailable returns a degraded response
    Given Jarvis is running without a connected NATS transport
    When Rich asks Jarvis to queue a build
    Then the supervisor should receive a degraded response indicating the NATS connection failed
    And a routing history entry should still be written recording the transport-unavailable outcome
    And the chat session should remain usable

  # Why: DDR-020 — the dispatch concurrency cap also covers queue_build
  # [ASSUMPTION: confidence=high] Shared dispatch cap = 8, covers both queue_build and dispatch_by_capability per DDR-020
  @task:TASK-J005-005
  @negative
  Scenario: Queueing a build when the dispatch concurrency cap is saturated returns a degraded response
    Given the supervisor's concurrent dispatch slots are all held by other in-flight work
    When Rich asks Jarvis to queue a build
    Then the supervisor should receive a degraded response indicating dispatch is overloaded
    And no build-queued request should be published to Forge
    And no correlation should be registered

  # Why: ADR-ARCH-021 — every error path must be a structured string, never an exception
  @task:TASK-J005-005
  @negative
  Scenario Outline: Queueing a build with invalid arguments returns a structured validation error
    When Rich asks Jarvis to queue a build with an <invalid_field>
    Then the supervisor should receive a structured validation error naming the offending field
    And no build-queued request should be published to Forge
    And no correlation should be registered

    Examples:
      | invalid_field                                                |
      | feature identifier that does not match the FEAT-XXX pattern  |
      | repository value that is not in org/name format              |
      | originating adapter that is not in the allowed adapter set   |

  # Why: DDR-031 — adapter identity is constitutional, not reasoning-adjustable
  @task:TASK-J005-005
  @negative @security
  Scenario: A reasoning-model attempt to override the originating adapter is silently overridden by the session adapter
    Given Rich's session uses the terminal adapter
    When the reasoning model invokes the queue tool claiming a different originating adapter
    Then the published build-queued request should record the session's terminal adapter
    And the reasoning model should not be told that its argument was overridden
    And no error path should be taken

  # ─── GROUP D: Edge Cases ────────────────────────────────────────────────

  # Why: Per-session isolation — notifications must not leak across concurrent sessions
  @task:TASK-J005-003
  @edge-case
  Scenario: A stage-complete event for a build queued from one session does not surface on a different session
    Given two terminal sessions are active for the same operator
    And Rich queued a build from the first session
    When Forge announces a stage of that build has completed
    Then only the first session's pending notifications should contain the new event
    And the second session's pending notifications should remain empty

  # Why: DDR-030 — notifications never interleave with the LLM stream or the user's typing
  @task:TASK-J005-007
  @edge-case
  Scenario: A notification arriving during a supervisor turn is buffered until the next prompt cycle
    Given Rich has just submitted a prompt and the supervisor is producing a reply
    When Forge announces a stage of an earlier build has completed
    Then the notification should not be rendered while the reply is being produced
    And the notification should be rendered before Rich is asked for the next prompt

  # Why: DDR-030 — end_session leaves no stranded notifications
  @task:TASK-J005-006
  @edge-case
  Scenario: Ending a session clears that session's pending notifications and discards future ones
    Given Rich's session has pending stage-complete notifications
    When Rich ends the session
    Then the session's pending notification queue should be cleared
    And the cleared count should be recorded in the operator log
    And any subsequent stage-complete event for a build queued from that session should be discarded without raising

  # Why: DDR-031 — the tool argument remains a fallback for sessionless test/scripted paths
  @task:TASK-J005-005
  @edge-case
  Scenario: Queueing a build without an active session uses the originating-adapter argument as a fallback
    Given there is no active session bound to the queue tool
    When the queue tool is invoked with an explicit originating adapter
    Then the published build-queued request should use the supplied originating adapter
    And the routing history entry should record the same adapter
    And no notification should be queued anywhere

  # Why: DDR-019 inheritance — Graphiti unavailability must not block the user-visible feedback loop
  @task:TASK-J005-004
  @edge-case
  Scenario: A failed stage-complete edge write is logged as a warning but does not affect notification delivery
    Given Rich has queued a build from this session
    And the routing history substrate is unavailable
    When Forge announces that a stage of the build has completed
    Then the stage-complete notification should still be queued for Rich's session
    And the failed edge write should be recorded in the operator log as a warning
    And the chat session should continue without error

  # Why: DDR-027 — deliver_policy=NEW means stage events from before subscription are intentionally not replayed
  @task:TASK-J005-008
  @edge-case
  Scenario: Stage-complete events that fired before the subscriber started are not delivered to the session
    Given Forge published stage-complete events while Jarvis was not running
    When Jarvis starts and creates its stage-complete subscription
    Then those earlier events should not be delivered to any session
    And only events Forge publishes after the subscription was created should be considered for delivery

  # Why: Defence against payload tampering — malformed JSON must not crash the subscriber
  @task:TASK-J005-003
  @edge-case @security
  Scenario: A stage-complete delivery whose body is not a valid envelope is dropped without raising
    Given Rich has queued a build from this session
    When a stage-complete delivery arrives whose body cannot be parsed as a message envelope
    Then no notification should be queued for any session
    And the malformed delivery should be reported in the operator log
    And the subscriber should remain healthy and continue processing later events

  # Why: Defence against payload schema drift — extra Forge-side fields must not break consumption
  @task:TASK-J005-003
  @edge-case @security
  Scenario: A stage-complete event carrying additional unknown fields is consumed without rejection
    Given Rich has queued a build from this session
    When Forge announces a stage of the build has completed with additional unknown fields in the payload
    Then a notification should still be queued for Rich's session
    And a stage-complete edge should still be recorded against the originating routing history entry

  # Why: Two operators (or two test fixtures) racing on the same correlation must each get their own routing
  @task:TASK-J005-003
  @edge-case @concurrency
  Scenario: Two stage-complete events for two different correlations arriving in the same instant each route to their own session
    Given two builds have been queued from two different sessions
    When stage-complete events for both builds are delivered concurrently
    Then each session should see only the notification for its own build
    And both originating routing history entries should each receive one new stage-complete edge

  # Why: Forge's contract emits multiple stages per build — bursts must preserve order on a single session
  @task:TASK-J005-007
  @edge-case @concurrency
  Scenario: A burst of stage-complete events for one build is rendered in publication order on the next prompt cycle
    Given Rich has queued a build from this session
    When Forge publishes five stage-complete events for that build in rapid succession
    Then the next prompt cycle should render the five notifications in publication order
    And five distinct stage-complete edges should be recorded against the originating routing history entry

  # Why: Forge dedupes by (feature_id, correlation_id); Jarvis must not register the same correlation twice
  # [ASSUMPTION: confidence=high] DDR-028 — duplicate correlation_id register updates the existing entry's LRU position
  @task:TASK-J005-003
  @edge-case
  Scenario: Re-using an explicit correlation identifier across two queue requests does not corrupt the correlation map
    Given Rich queued a build with an explicit correlation identifier
    When Rich queues a second build supplying the same correlation identifier
    Then the correlation map should hold a single entry for that correlation identifier
    And subsequent stage-complete events for that correlation should route to the most-recent originating session

  # Why: A stage event whose correlation was just evicted must not silently overwrite a different entry
  @task:TASK-J005-003
  @edge-case
  Scenario: A stage-complete event arriving after its correlation has been evicted is dropped without affecting any other correlation
    Given a build's correlation has been evicted from the correlation map due to overflow
    When a stage-complete event for that evicted correlation arrives
    Then no notification should be queued for any session
    And no other correlation's stage-complete edges should be modified

  # Why: Shutdown must not hang on a wedged broker
  # [ASSUMPTION: confidence=high] Subscriber stop timeout is 5 seconds per API-internal §1
  @task:TASK-J005-009
  @edge-case @integration
  Scenario: Stopping the subscriber during shutdown completes within the bounded timeout even when the broker is unresponsive
    Given Jarvis is shutting down
    And the broker is unresponsive to drain requests
    When the subscriber is asked to stop with the configured shutdown timeout
    Then the subscriber should report stopped within the timeout
    And the timeout escalation should be recorded in the operator log
    And shutdown should proceed to the remaining steps

  # Why: queue_build is published via JetStream; specialist dispatch is core-NATS request/reply — they must not interfere
  @task:TASK-J005-005
  @edge-case @integration
  Scenario: A build queue and a specialist dispatch issued in parallel each consume one slot from the shared concurrency cap
    Given two of the supervisor's concurrent dispatch slots are free
    When Rich asks Jarvis to queue a build and dispatch a specialist at the same time
    Then both requests should proceed
    And two slots should be observed as in-flight while both are running
    And both slots should be released once each request completes
