# Generated by /feature-spec
# Feature: Project Scaffolding, Supervisor Skeleton & Session Lifecycle (FEAT-JARVIS-001)
# Stack: python (Python 3.12)
# Assumptions: 6 (see project-scaffolding-supervisor-sessions_assumptions.yaml)
# Generated: 2026-04-21T14:00:00Z

@feat-jarvis-001 @foundation
Feature: Project Scaffolding, Supervisor Skeleton & Session Lifecycle
  As Rich, the attended operator of the Jarvis fleet surface
  I want a runnable jarvis package, a buildable DeepAgents supervisor,
    a CLI that starts conversations, and cross-session fact recall
  So that I can have a useful conversation with Jarvis on day 1
    and every subsequent v1 feature lands on a stable scaffold

  Background:
    Given the jarvis package has been installed into a clean Python 3.12 environment
    And no sessions are currently live
    And the supervisor model is configured to return deterministic canned responses for tests

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core day-1 success criterion — Rich can hold a conversation from the CLI
  @key-example @smoke
  Scenario: Rich starts a conversation and receives a supervisor response
    Given the required provider configuration is in place
    When Rich runs "jarvis chat"
    And Rich enters "Hi Jarvis"
    Then the session should start successfully
    And Rich should see the supervisor's reply

  # Why: A conversation must end cleanly on the documented exit signals
  # [ASSUMPTION: confidence=low] "/exit" matches case-sensitively with leading/trailing whitespace trimmed
  @key-example @smoke
  Scenario Outline: Rich ends a chat session cleanly
    Given Rich has started a chat session
    When Rich <end-signal>
    Then the session should end
    And a "session ended." banner should be shown
    And the process should exit with success

    Examples:
      | end-signal                |
      | types "/exit"             |
      | sends end-of-input (EOF)  |

  # Why: "version" is the smallest self-test for the installed package
  @key-example @smoke
  Scenario: Rich checks the installed jarvis version
    When Rich runs "jarvis version"
    Then the package version should be printed on a single line
    And the command should exit with success
    And no configuration should be loaded

  # Why: "health" is the wiring-debug primitive — validates config + builds the supervisor without spending tokens
  @key-example @smoke
  Scenario: Rich checks that the scaffold is healthy before a conversation
    Given the required provider configuration is in place
    When Rich runs "jarvis health"
    Then a status report should summarise the configuration
    And the report should indicate that the supervisor builds successfully
    And the report should indicate that the memory store is ready
    And the command should exit with success

  # Why: The day-1 cross-session recall criterion — Memory Store is keyed per user
  @key-example @smoke
  Scenario: A fact stated in one session is recalled in a later session for the same user
    Given Rich has had a chat session in which he stated "my DDD Southwest talk is on 16 May"
    And that session has ended
    When Rich starts a new chat session as the same user
    And Rich asks "when is my DDD talk?"
    Then the supervisor's reply should reference 16 May

  # Why: Running "jarvis" with no arguments should be discoverable (prints command list)
  @key-example
  Scenario: Running jarvis with no command prints the available commands
    When Rich runs "jarvis"
    Then the available commands should be listed
    And the command should exit with success

  # Why: Supervisor factory is the public contract consumed by every later feature
  @key-example
  Scenario: The supervisor factory produces a compiled graph with Phase 1 built-ins
    Given a valid configuration
    When build_supervisor is called with the configuration
    Then a compiled supervisor graph should be returned
    And the built-in tools "write_todos", virtual filesystem, and "task" should be enabled
    And the built-in tool "execute" should be disabled
    And no custom tools should be registered
    And no subagents should be registered

  # Why: Session identity is the stable primitive every later feature extends
  @key-example
  Scenario: Starting a session mints a new session with a stable identity
    When a CLI session is started for the user "rich"
    Then a Session object should be created
    And the session's thread_id should equal its session_id
    And the session's session_id should follow the documented adapter-prefixed pattern
    And a SessionStarted event should be emitted to the structured log

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — two sessions started in quick succession must have distinct identity
  @boundary
  Scenario: Two successive session starts return distinct session identities
    When two CLI sessions are started for the same user
    Then the two session_ids should differ
    And the two thread_ids should differ
    And each session_id should match the documented adapter-prefixed pattern

  # Why: Just-outside boundary — adapter values other than CLI are reserved and must be refused in Phase 1
  # [ASSUMPTION: confidence=medium] The refusal surfaces as a JarvisError naming the adapter
  @boundary @negative
  Scenario Outline: Non-CLI adapters are refused until their adapter feature ships
    When a session start is attempted with adapter "<adapter>"
    Then the session start should be refused with a JarvisError
    And the error message should reference the adapter name

    Examples:
      | adapter   |
      | telegram  |
      | dashboard |
      | reachy    |

  # Why: Default configuration loads with no env overrides (zero-config happy path)
  @boundary
  Scenario: Default configuration loads with no environment overrides
    Given no JARVIS_ environment variables are set
    When the configuration is loaded
    Then the log level should default to "INFO"
    And the memory store backend should default to "in_memory"
    And the supervisor model should default to the llama-swap alias

  # Why: Memory Store namespace scheme is load-bearing — pin the exact layout
  @boundary
  Scenario: Memory Store entries are namespaced by user, not by session
    Given the supervisor has written a fact during a session for user "rich"
    Then the fact should be stored under a namespace whose first segment is "user"
    And the second segment of the namespace should be the user_id
    And the namespace should contain no session_id segment

  # Why: end_session must be idempotent so adapter/CLI shutdown paths can call it unconditionally
  @boundary
  Scenario: end_session is idempotent
    Given a live session exists
    When end_session is called for that session_id
    And end_session is called again for the same session_id
    Then both calls should succeed
    And the session should be marked ended exactly once

  # Why: Empty-input turn is the smallest non-degenerate REPL input
  # [ASSUMPTION: confidence=medium] A blank-line turn is silently skipped — no supervisor invocation, no event
  @boundary
  Scenario: An empty chat turn is handled without breaking the REPL
    Given Rich has started a chat session
    When Rich submits an empty line
    Then the REPL should continue accepting input
    And no supervisor invocation should be recorded for that empty turn

  # Why: Chat exit code on clean exit is the documented contract (0)
  @boundary
  Scenario: A chat session that receives no turns before EOF exits cleanly
    Given Rich has started a chat session
    When Rich sends end-of-input immediately
    Then the session should end
    And the process should exit with success

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: The default supervisor model points at llama-swap — missing base URL must fail loud
  @negative
  Scenario: Default supervisor model without OPENAI_BASE_URL fails with a clear configuration error
    Given the supervisor model is left at its default
    And OPENAI_BASE_URL is not set
    When jarvis health is run
    Then the command should fail with a configuration error
    And the error should name OPENAI_BASE_URL
    And the process should exit with code 1

  # Why: A cloud-provider-prefixed model must fail loud when its key is absent
  @negative
  Scenario Outline: A model that requires a provider key fails when the key is missing
    Given the supervisor model is set to "<model>"
    And "<env_var>" is not set
    When jarvis health is run
    Then the command should fail with a configuration error
    And the error should name "<env_var>"
    And the process should exit with code 1

    Examples:
      | model                         | env_var            |
      | anthropic:claude-haiku-4-5    | ANTHROPIC_API_KEY  |
      | google_genai:gemini-3-flash   | GOOGLE_API_KEY     |

  # Why: Malformed model strings must be rejected at config time, not at invoke time
  # [ASSUMPTION: confidence=medium] Pydantic ValidationError at config load exits the CLI with code 1, same as ConfigurationError
  @negative
  Scenario: A supervisor model string with no provider prefix is rejected at config load
    Given JARVIS_SUPERVISOR_MODEL is set to "jarvis-reasoner"
    When the configuration is loaded
    Then configuration loading should fail with a validation error
    And the process should exit with code 1

  # Why: Phase 1 only implements in_memory; file and graphiti backends must refuse at startup
  @negative
  Scenario Outline: Unsupported memory store backends are refused at startup
    Given JARVIS_MEMORY_STORE_BACKEND is set to "<backend>"
    When lifecycle startup runs
    Then startup should fail with a configuration error
    And the error should indicate that the backend is not implemented in this phase

    Examples:
      | backend  |
      | file     |
      | graphiti |

  # Why: Unknown session id must fail loudly so future adapter code cannot silently drop turns
  @negative
  Scenario: Resuming an unknown session raises SessionNotFoundError
    When resume_session is called with an unknown session_id
    Then a SessionNotFoundError should be raised

  # Why: Secrets must never leak via repr, logs, or status output
  @negative
  Scenario: Rendering the configuration does not disclose provider secrets
    Given provider API keys are set to known sensitive values
    When the configuration is converted to a string or logged
    Then the sensitive values should not appear in the output
    And the keys should be masked

  # Why: Invalid log levels must fail at config load, not silently degrade to a default
  # [ASSUMPTION: confidence=medium] Pydantic ValidationError at config load exits the CLI with code 1, same as ConfigurationError
  @negative
  Scenario: An invalid log level is rejected at configuration load
    Given JARVIS_LOG_LEVEL is set to "bogus"
    When the configuration is loaded
    Then configuration loading should fail with a validation error
    And the process should exit with code 1

  # Why: Provider errors during invoke must not kill the REPL — the conversation recovers
  @negative
  Scenario: A provider error during a chat turn is surfaced but the REPL continues
    Given Rich has started a chat session
    And the next supervisor invocation will raise a provider error
    When Rich submits a turn
    Then an error line prefixed with "[error]" should be printed
    And the REPL should continue accepting the next turn
    And the session should not be ended

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: SIGINT mid-chat must exit with 130 and still clean up the live session
  @edge-case
  Scenario: Pressing Ctrl-C during a chat session exits with 130 and cleans up the session
    Given Rich has started a chat session
    When a SIGINT signal is delivered to the process
    Then the session should be ended
    And a SessionEnded event should be emitted
    And the process should exit with code 130

  # Why: End-to-end smoke — the shell is structurally sound when mocked-LLM responses flow through the whole stack
  @edge-case @smoke
  Scenario: End-to-end smoke test — CLI input produces CLI output via a mocked supervisor
    Given the supervisor is configured with a canned response "Hello, Rich."
    When Rich runs "jarvis chat" and submits a single turn
    Then the canned response should be printed to stdout
    And the session should end cleanly on end-of-input

  # Why: Lifecycle ordering — logging must be configured before config validation so errors are traceable
  @edge-case
  Scenario: Startup configures logging before validating configuration
    Given an invalid configuration is about to be loaded
    When lifecycle startup runs
    Then structured logging should already be configured
    And the configuration failure should be emitted as a structured log event

  # Why: Jarvis restart is acceptable loss — live sessions do not persist across process boundaries (ADR-ARCH-008)
  @edge-case
  Scenario: A Jarvis restart invalidates live sessions
    Given a live session exists
    When the Jarvis process is restarted
    Then resuming the previous session_id in the new process should fail with SessionNotFoundError

  # Why: Module-boundary invariant — domain code must not import adapters or tools
  @edge-case @regression
  Scenario: Domain modules do not import from adapter or tool layers
    When the import graph of the jarvis.sessions package is inspected
    Then it should not import from jarvis.adapters
    And it should not import from jarvis.tools

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E — Edge Case Expansion: Security
  # ─────────────────────────────────────────────────────────────────────────

  # Why: .env is the only secret-bearing file — git-ignoring it is the first line of defence
  @edge-case @security
  Scenario: The .env file is git-ignored
    Given the repository has a .gitignore
    Then ".env" should be listed as an ignored pattern
    And ".env.example" should be committed as a template

  # Why: The structlog redaction processor must catch accidental secret logging belt-and-braces with SecretStr
  @edge-case @security @regression
  Scenario: Structured log events redact provider-key and token fields
    Given structured logging has been configured
    And provider API keys are set to known sensitive values
    When a log event is emitted carrying the full configuration
    Then any field whose name ends in "_key" should be masked in the emitted event
    And any field whose name ends in "_token" should be masked in the emitted event
    And the sensitive values should not appear in the rendered log output

  # Why: Memory Store namespace isolation is what lets Phase 1 commit to a multi-user path without rework
  @edge-case @security
  Scenario: Memory Store entries written for one user are not recalled for another user
    Given the supervisor has written a fact during a session for user "rich"
    When the supervisor runs a new session for a different user_id
    And the supervisor attempts to recall that fact
    Then the fact should not be returned

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP F — Edge Case Expansion: Concurrency
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Single-threaded contract must be explicit so FEAT-JARVIS-006 Telegram knows what to revisit
  # [ASSUMPTION: confidence=low] A second concurrent invoke on the same session is refused with an error rather than silently serialised
  @edge-case @concurrency
  Scenario: The SessionManager does not support concurrent invokes on the same session in Phase 1
    Given Rich has started a chat session
    And an invoke call for that session is already in flight
    When a second invoke call is made for the same session before the first completes
    Then the second call should be refused with a clear error
    And the outcome should be documented as a Phase 1 constraint, not a silent race

  # Why: REPL-level serialisation protects the single-threaded contract at the user-facing boundary
  # [ASSUMPTION: confidence=medium] The REPL reads the next line only after the prior reply has been printed
  @edge-case @concurrency
  Scenario: Chat REPL serialises turns one at a time
    Given Rich has started a chat session
    When Rich submits a turn
    Then the REPL should not read the next line from standard input until the supervisor's reply for the current turn has been printed

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP G — Edge Case Expansion: Integration Boundaries
  # ─────────────────────────────────────────────────────────────────────────

  # Why: llama-swap is the single inference front door — its unavailability must degrade gracefully, not kill the shell
  @edge-case @integration
  Scenario: An unreachable llama-swap endpoint surfaces as an error in the REPL without ending the session
    Given the supervisor model is configured to reach llama-swap
    And the llama-swap endpoint is unreachable
    When Rich starts a chat session and submits a turn
    Then an error line prefixed with "[error]" should be printed
    And the REPL should continue accepting the next turn
    And the session should not be ended

  # Why: build_supervisor must be token-free so jarvis health is safe to run constantly during AutoBuild
  @edge-case @integration @regression
  Scenario: build_supervisor does not invoke the language model
    Given a valid configuration
    When build_supervisor is called
    Then no request should be issued to the configured model endpoint
    And the compiled supervisor graph should be returned successfully
