# Generated by /feature-spec
# Feature: FEAT-JARVIS-INTERNAL-001 Documentation Foundation
# Stack: python
# Assumptions: 13 (see feat-jarvis-internal-001-documentation-foundation_assumptions.yaml)
# Generated: 2026-04-30T11:45:00Z

@feat-jarvis-internal-001 @docs @phase-3-close
Feature: FEAT-JARVIS-INTERNAL-001 Documentation Foundation
  As a Phase-3-close steward
  I want the five new FEAT-J004/J005 infrastructure modules and the repo README
  to share a consistent, current shape
  So that human readers landing on the repo and Forge's Step-14 e2e round-trip
  both have a clean, navigable payload

  Background:
    Given the repository is at the Phase-3-close state on `main`
    And the candidate files are the five FEAT-J004/J005 infrastructure modules and the repo-root `README.md`
    And reasoning-model-facing tool docstrings under `src/jarvis/tools/` are explicitly out of scope per the FEAT-JARVIS-004/-005 invariant

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # GROUP A — Key Examples (9 scenarios, 4 are outlines × 5 modules = 25 effective rows)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  # Why: Every new infrastructure module must declare its purpose up front
  # [ASSUMPTION: confidence=medium] Purpose paragraph is at least 2 complete sentences (ASSUM-008)
  @task:TASK-DOC-007
  @key-example @smoke
  Scenario Outline: Each infrastructure module has a Purpose paragraph
    Given the module file <module>
    When the module docstring is read
    Then the docstring's first paragraph should describe the module's purpose
    And the paragraph should contain at least 2 complete sentences

    Examples:
      | module                                              |
      | src/jarvis/infrastructure/nats_client.py            |
      | src/jarvis/infrastructure/fleet_registration.py     |
      | src/jarvis/infrastructure/capabilities_registry.py  |
      | src/jarvis/infrastructure/routing_history.py        |
      | src/jarvis/infrastructure/forge_notifications.py    |

  # Why: Origin attribution lets future readers trace each module to its feature plan
  @task:TASK-DOC-007
  @key-example @smoke
  Scenario Outline: Each infrastructure module references its FEAT-JARVIS origin
    Given the module file <module>
    When the module docstring is read
    Then the docstring should reference <feature> as its origin

    Examples:
      | module                                              | feature         |
      | src/jarvis/infrastructure/nats_client.py            | FEAT-JARVIS-004 |
      | src/jarvis/infrastructure/fleet_registration.py     | FEAT-JARVIS-004 |
      | src/jarvis/infrastructure/capabilities_registry.py  | FEAT-JARVIS-004 |
      | src/jarvis/infrastructure/routing_history.py        | FEAT-JARVIS-004 |
      | src/jarvis/infrastructure/forge_notifications.py    | FEAT-JARVIS-005 |

  # Why: Each module's behavioural decisions are pinned by DDRs — readers should be able to navigate to them
  @task:TASK-DOC-007
  @key-example
  Scenario Outline: Each infrastructure module cites at least one DDR
    Given the module file <module>
    When the module docstring is read
    Then the docstring should cite at least one DDR identifier
    And each cited DDR identifier should resolve to a file under <ddr_dir>

    Examples:
      | module                                              | ddr_dir                                |
      | src/jarvis/infrastructure/nats_client.py            | docs/design/FEAT-JARVIS-004/decisions/ |
      | src/jarvis/infrastructure/fleet_registration.py     | docs/design/FEAT-JARVIS-004/decisions/ |
      | src/jarvis/infrastructure/capabilities_registry.py  | docs/design/FEAT-JARVIS-004/decisions/ |
      | src/jarvis/infrastructure/routing_history.py        | docs/design/FEAT-JARVIS-004/decisions/ |
      | src/jarvis/infrastructure/forge_notifications.py    | docs/design/FEAT-JARVIS-005/decisions/ |

  # Why: Each module should link to its design doc so readers can get the full architectural context
  @task:TASK-DOC-007
  @key-example
  Scenario Outline: Each infrastructure module links to its design doc
    Given the module file <module>
    When the module docstring is read
    Then the docstring should reference the design doc at <design_doc>

    Examples:
      | module                                              | design_doc                            |
      | src/jarvis/infrastructure/nats_client.py            | docs/design/FEAT-JARVIS-004/design.md |
      | src/jarvis/infrastructure/fleet_registration.py     | docs/design/FEAT-JARVIS-004/design.md |
      | src/jarvis/infrastructure/capabilities_registry.py  | docs/design/FEAT-JARVIS-004/design.md |
      | src/jarvis/infrastructure/routing_history.py        | docs/design/FEAT-JARVIS-004/design.md |
      | src/jarvis/infrastructure/forge_notifications.py    | docs/design/FEAT-JARVIS-005/design.md |

  # Why: README is the human entry point and must have an unambiguous H1
  @task:TASK-DOC-006
  @key-example @smoke
  Scenario: The repo README has an H1 with the project name
    Given the file `README.md`
    When the file is read
    Then the first heading should be a level-1 heading
    And the heading should contain "Jarvis"

  # Why: Status section communicates the current phase to anyone landing on the README
  # [ASSUMPTION: confidence=medium] Status section references the literal string "Phase 3" (ASSUM-006)
  @task:TASK-DOC-006
  @key-example @smoke
  Scenario: The repo README declares the current Phase-3-close status
    Given the file `README.md`
    When the file is read
    Then it should contain a "Status" section
    And the Status section should reference "Phase 3" by name
    And the Status section should describe the Phase 3 close criterion as the end-to-end Forge round-trip

  # Why: A Quick Start that matches the canonical commands prevents drift between human and AI docs
  # [ASSUMPTION: confidence=high] Canonical install = `uv sync`; canonical runtime = `python -m langgraph dev` (ASSUM-013, OVERRIDDEN)
  @task:TASK-DOC-006
  @key-example
  Scenario: The repo README Quick Start matches the canonical install/run commands
    Given the file `README.md`
    And the canonical install command is `uv sync`
    And the canonical runtime command is `python -m langgraph dev`
    When the README is read
    Then it should contain a "Quick Start" section
    And the Quick Start should include the canonical install command
    And the Quick Start should include the canonical runtime command

  # Why: Architecture section gives readers the entry point into the deeper docs
  @task:TASK-DOC-006
  @key-example
  Scenario: The repo README links to the architecture document
    Given the file `README.md`
    When the file is read
    Then it should contain an "Architecture" section
    And the Architecture section should link to `docs/architecture/ARCHITECTURE.md`

  # Why: Design Decisions section maps the ADR + DDR landscape for navigation
  # [ASSUMPTION: confidence=medium] Section explicitly references both J004 and J005 DDR directories (ASSUM-007)
  @task:TASK-DOC-006
  @key-example
  Scenario: The repo README catalogues the design-decision locations
    Given the file `README.md`
    When the file is read
    Then it should contain a "Design Decisions" section
    And the section should reference the ADR directory `docs/architecture/decisions/`
    And the section should reference the FEAT-JARVIS-004 DDR directory
    And the section should reference the FEAT-JARVIS-005 DDR directory

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # GROUP B — Boundary Conditions (2 scenarios, 1 outline × 4 examples = 5 effective rows)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  # Why: Just-inside / just-outside boundary pair — README must not shrink to a stub or balloon into a manual
  # [ASSUMPTION: confidence=medium] README line bounds 100–300 (ASSUM-004 + ASSUM-005)
  @task:TASK-DOC-006
  @boundary
  Scenario Outline: README line count is checked against the documented bounds
    Given a candidate `README.md` with <line_count> lines
    When the file's line count is computed
    Then the line count <verdict>

    Examples:
      | line_count | verdict                                |
      | 100        | should be accepted at the lower bound  |
      | 300        | should be accepted at the upper bound  |
      | 99         | should be rejected below the lower bound |
      | 301        | should be rejected above the upper bound |

  # Why: Module docstrings shouldn't dwindle to one-liners or sprawl into prose
  # [ASSUMPTION: confidence=low] Module docstring line bounds 20–250 (ASSUM-001 + ASSUM-002)
  @task:TASK-DOC-007
  @boundary
  Scenario: Each infrastructure module docstring is within the documented length bounds
    Given an infrastructure module under `src/jarvis/infrastructure/`
    And the module is one of the five candidates
    When the module docstring's line count is computed
    Then the line count should be at least 20
    And the line count should be at most 250

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # GROUP C — Negative Cases (5 scenarios)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  # Why: The reasoning model has been routing against the current tool docstrings since Phase 2 — touching them is a behavioural confound during the Step-14 e2e validator
  # [ASSUMPTION: confidence=high] Tool-docstring scope = `src/jarvis/tools/*.py` excluding `__init__.py` (ASSUM-012)
  @task:TASK-DOC-007
  @negative @smoke
  Scenario: Reasoning-model-facing tool docstrings remain byte-unchanged
    Given the files matching `src/jarvis/tools/*.py` excluding `__init__.py`
    And the docstrings of the `@tool`-decorated functions on `main` HEAD prior to this feature
    When the same docstrings are inspected after this feature is applied
    Then each tool docstring should be byte-identical to its prior version
    And no `@tool`-decorated function's docstring should be added, removed, or rewritten

  # Why: This feature is documentation-only — runtime behaviour mustn't shift
  @task:TASK-DOC-007
  @negative
  Scenario: No executable code is modified
    Given the diff of this feature against `main`
    When the changed lines are inspected
    Then every changed line should be inside a Python docstring or inside `README.md`
    And no executable Python statement should be modified

  # Why: A broken design-doc link is worse than no link
  @task:TASK-DOC-007
  @negative
  Scenario: Cited design-doc paths must resolve to real files
    Given each polished module docstring
    When the design-doc references in the docstring are extracted
    Then each referenced file should exist on disk
    And each referenced file should be readable

  # Why: Internal task IDs are GuardKit bookkeeping and should not leak into reader-facing prose
  # [ASSUMPTION: confidence=low] TASK-Jxxx references banned ENTIRELY from polished docstrings (ASSUM-003, OVERRIDDEN — was: trailing-section allowance)
  @task:TASK-DOC-007
  @negative @smoke
  Scenario: Polished docstrings contain no TASK-Jxxx references
    Given a polished module docstring (any of the five candidates)
    When the full text of the docstring is inspected
    Then it should contain no token matching the pattern `TASK-J\d{3}-\d{3}`
    And origin attribution should use the FEAT-JARVIS-XXX form only

  # Why: README must not reintroduce stale phase info
  @task:TASK-DOC-006
  @negative
  Scenario: The README does not mention "Pre-Architecture" status
    Given the file `README.md`
    When the file is read
    Then the file should not contain the literal phrase "Pre-Architecture"
    And the file should not declare a hard-coded passing-test count below the current count

  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  # GROUP D — Edge Cases (5 scenarios)
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  # Why: A docstring change must not break the import; this is structurally important
  @task:TASK-DOC-007
  @edge-case @smoke
  Scenario: All polished modules remain importable and graphs still compile
    Given the polished modules
    When each module is imported by Python
    Then every import should succeed
    And `langgraph dev` should still start
    And both the `jarvis` and `jarvis_reasoner` graphs should compile

  # Why: Documentation-only changes shouldn't regress tests or coverage
  # [ASSUMPTION: confidence=high] Coverage floor 92% (ASSUM-010)
  @task:TASK-DOC-007
  @edge-case @smoke
  Scenario: The full pytest suite remains green and coverage does not regress
    Given the polished feature is applied
    When `uv run pytest tests/` is run
    Then every test should pass
    And the line coverage should not regress below 92%

  # Why: Type checking must not regress relative to pre-feature state
  # [ASSUMPTION: confidence=high] mypy delta = no new errors in any file modified by this feature (ASSUM-011)
  @task:TASK-DOC-007
  @edge-case
  Scenario: No new mypy errors are introduced by polished files
    Given the polished feature is applied
    And the set of files modified by this feature
    When `uv run mypy src/jarvis/` is run
    Then no new mypy error should appear in any file modified by this feature
    And any pre-existing mypy errors are out of scope for this feature

  # Why: Cross-repo links should be relative for portability
  # [ASSUMPTION: confidence=medium] README in-repo references must be relative paths (ASSUM-009)
  @task:TASK-DOC-006
  @edge-case
  Scenario: README in-repo references use relative paths
    Given the file `README.md`
    When markdown links to files in this repo are inspected
    Then each in-repo link should be a relative path
    And no in-repo link should hard-code an absolute filesystem path

  # Why: Docstring polish must not silently drop existing high-value DDR/ADR cross-refs
  @task:TASK-DOC-003
  @edge-case
  Scenario: Existing DDR-021 / ADR-ARCH-017 references in capabilities_registry.py are preserved
    Given the docstring of `src/jarvis/infrastructure/capabilities_registry.py`
    When the polished docstring is compared against the prior docstring
    Then the polished docstring should still cite DDR-021
    And the polished docstring should still cite ADR-ARCH-017
