# Generated by /feature-spec
# Feature: Core Tools & Capability-Driven Dispatch Tools
# Stack: python
# Assumptions: 6 (see feat-jarvis-002-core-tools-and-dispatch_assumptions.yaml)
# Generated: 2026-04-23T00:00:00Z

@feat-jarvis-002
Feature: Core Tools & Capability-Driven Dispatch Tools
  As the Jarvis supervisor's reasoning model
  I want a stable set of tools for reading files, searching the web, doing
  arithmetic, inspecting the fleet's capability catalogue, and dispatching
  work to specialists or the build queue
  So that I can act as a useful general-purpose agent before any NATS transport
  is wired

  Background:
    Given Jarvis has started with a configured workspace and a stub capability registry
    And the registry lists architect-agent, product-owner-agent, ideation-agent, and forge
    And every tool is registered on the supervisor with its docstring as the contract

  # ---------------------------------------------------------------------------
  # GROUP A — Key Examples
  # ---------------------------------------------------------------------------

  # Why: Core path for read_file — the supervisor reads a valid workspace file
  @task:TASK-J002-008
  @key-example @smoke
  Scenario: Reading a UTF-8 text file inside the workspace returns its contents
    Given a UTF-8 text file exists inside the workspace
    When the supervisor reads the file
    Then the tool returns the file contents as a string

  # Why: Core path for search_web with the configured Tavily provider
  @task:TASK-J002-009
  @key-example @smoke
  Scenario: Searching the web with a configured provider returns result summaries
    Given the web-search provider is configured with a valid key
    When the supervisor searches the web for a non-empty query
    Then the tool returns a list of search results with titles, URLs, snippets, and scores

  # Why: Core path for calculate — arithmetic is delegated, not reasoned
  @task:TASK-J002-011
  @key-example @smoke
  Scenario: Evaluating a supported arithmetic expression returns a numeric result
    When the supervisor asks the calculator to evaluate "15% of 847"
    Then the tool returns the computed numeric result as a string

  # Why: Stubbed calendar returns empty list with stable signature for later skills
  @task:TASK-J002-010
  @key-example @smoke
  Scenario: Retrieving calendar events in Phase 2 returns an empty list
    When the supervisor requests calendar events for today
    Then the tool returns an empty list of events
    And the returned shape matches the signature expected by the morning-briefing skill

  # Why: Capability catalogue is the fleet-is-catalogue pattern
  @task:TASK-J002-012
  @key-example @smoke
  Scenario: Listing available capabilities returns the current stub registry
    When the supervisor requests the capability catalogue
    Then the tool returns all four registered descriptors with their roles, descriptions, cost and latency signals, and tool lists

  # Why: Core dispatch path — capability-driven resolution to a specialist
  @task:TASK-J002-013
  @key-example @smoke
  Scenario: Dispatching by capability resolves a specialist and returns a successful result
    Given the reasoning model has identified run_architecture_session as the required capability
    When the supervisor dispatches by capability with a valid JSON payload
    Then the tool resolves the request to the architect specialist
    And the tool returns a successful specialist result payload
    And the dispatch is recorded for trace-richness compatibility

  # Why: Core queue_build path — Forge receives a valid build request
  @task:TASK-J002-014
  @key-example @smoke
  Scenario: Queueing a build for a planned feature returns an acknowledgement
    Given the user has an already-planned feature with a valid feature id and repo
    When the supervisor queues the build via Jarvis
    Then the tool returns an acknowledgement containing the feature id, correlation id, queued time, publish target, and status queued
    And the constructed build-queued payload records Jarvis as the trigger and the terminal adapter as the origin

  # Why: Capabilities are also injected into the supervisor prompt (DDR-008)
  @task:TASK-J002-016
  @key-example
  Scenario: The capability catalogue is injected into the supervisor system prompt at session start
    When the supervisor graph is built with the stub registry
    Then the rendered system prompt contains a block for each registered capability including its role, description, cost signal, latency signal, and tools

  # Why: Assembly is a single wiring point for the nine tools
  @task:TASK-J002-015
  @key-example
  Scenario: The supervisor is built with all nine Phase 2 tools wired
    When the tool list is assembled with the configuration and the capability registry
    Then the supervisor exposes read_file, search_web, get_calendar_events, calculate, list_available_capabilities, capabilities_refresh, capabilities_subscribe_updates, dispatch_by_capability, and queue_build
    And the tools appear in stable alphabetical order to avoid prompt-cache churn

  # ---------------------------------------------------------------------------
  # GROUP B — Boundary Conditions
  # ---------------------------------------------------------------------------

  # Why: Just-inside / just-outside boundary for file size limit
  @task:TASK-J002-008
  @boundary
  Scenario Outline: read_file enforces the one megabyte file size limit
    Given a text file exists inside the workspace with size <size>
    When the supervisor reads the file
    Then the outcome is <outcome>

    Examples:
      | size                  | outcome                                              |
      | exactly 1 megabyte    | the file contents are returned                       |
      | one byte under 1MB    | the file contents are returned                       |
      | one byte over 1MB     | the tool rejects the file as too large               |
      | 10 megabytes          | the tool rejects the file as too large               |

  # Why: max_results range for search_web is 1..10
  @task:TASK-J002-009
  @boundary
  Scenario Outline: search_web accepts max_results only within its documented range
    Given the web-search provider is configured with a valid key
    When the supervisor searches the web with max_results <value>
    Then the outcome is <outcome>

    Examples:
      | value | outcome                                                            |
      | 1     | up to one search result is returned                                |
      | 5     | up to five search results are returned                             |
      | 10    | up to ten search results are returned                              |
      | 0     | the tool rejects the request as invalid max_results                |
      | 11    | the tool rejects the request as invalid max_results                |

  # Why: dispatch timeout bounds 5..600
  @task:TASK-J002-013
  @boundary
  Scenario Outline: dispatch_by_capability accepts timeout_seconds only within 5 to 600
    Given the reasoning model has identified a resolvable capability
    When the supervisor dispatches with timeout_seconds <value>
    Then the outcome is <outcome>

    Examples:
      | value | outcome                                                   |
      | 5     | the dispatch proceeds with the requested timeout          |
      | 60    | the dispatch proceeds with the requested timeout          |
      | 600   | the dispatch proceeds with the requested timeout          |
      | 4     | the tool rejects the request as invalid timeout           |
      | 601   | the tool rejects the request as invalid timeout           |

  # Why: calculate boundary around division-by-zero
  @task:TASK-J002-011
  @boundary @negative
  Scenario: Calculating an expression that divides by zero returns a structured error
    When the supervisor asks the calculator to evaluate an expression that divides by zero
    Then the tool returns a structured error indicating division by zero

  # Why: calculate boundary around numeric overflow
  @task:TASK-J002-011
  @boundary @negative
  Scenario: Calculating an expression that exceeds the float range returns an overflow error
    When the supervisor asks the calculator to evaluate an expression whose result exceeds the representable float range
    Then the tool returns a structured error indicating overflow

  # Why: feature_id pattern boundary for queue_build
  @task:TASK-J002-014
  @boundary
  Scenario Outline: queue_build validates feature_id against the documented pattern
    Given the user has a planned feature in a valid repository
    When the supervisor queues the build with feature id <feature_id>
    Then the outcome is <outcome>

    Examples:
      | feature_id            | outcome                                         |
      | FEAT-AB1              | the build is acknowledged                       |
      | FEAT-JARVIS-EXAMPLE01 | the build is acknowledged                       |
      | FEAT-AB               | the tool rejects the feature id as invalid      |
      | feat-jarvis-002       | the tool rejects the feature id as invalid      |
      | BUG-JARVIS-001        | the tool rejects the feature id as invalid      |

  # Why: repo pattern boundary
  @task:TASK-J002-014
  @boundary
  Scenario Outline: queue_build validates repo against the org/name pattern
    Given the user has a planned feature with a valid feature id
    When the supervisor queues the build against repo <repo>
    Then the outcome is <outcome>

    Examples:
      | repo                   | outcome                                         |
      | guardkit/jarvis        | the build is acknowledged                       |
      | appmilla/forge         | the build is acknowledged                       |
      | guardkit               | the tool rejects the repo as invalid            |
      | guardkit/jarvis/extra  | the tool rejects the repo as invalid            |

  # Why: originating_adapter literal boundary
  @task:TASK-J002-014
  @boundary
  Scenario Outline: queue_build restricts originating_adapter to the documented values
    Given the user has a planned feature in a valid repository
    When the supervisor queues the build with originating adapter <adapter>
    Then the outcome is <outcome>

    Examples:
      | adapter       | outcome                                           |
      | terminal      | the build is acknowledged                         |
      | telegram      | the build is acknowledged                         |
      | dashboard     | the build is acknowledged                         |
      | voice-reachy  | the build is acknowledged                         |
      | email         | the tool rejects the adapter as invalid           |
      | TERMINAL      | the tool rejects the adapter as invalid           |

  # ---------------------------------------------------------------------------
  # GROUP C — Negative Cases
  # ---------------------------------------------------------------------------

  # Why: Path traversal must be refused by read_file
  @task:TASK-J002-008
  @negative
  Scenario: Reading a path outside the workspace returns a path traversal error
    When the supervisor reads a path that resolves outside the configured workspace root
    Then the tool returns a structured error indicating the path traverses outside the workspace

  # Why: Missing files produce structured errors, not exceptions
  @task:TASK-J002-008
  @negative
  Scenario: Reading a path that does not exist returns a not-found error
    When the supervisor reads a path that does not exist
    Then the tool returns a structured error indicating the file was not found

  # Why: Directory reads are rejected
  @task:TASK-J002-008
  @negative
  Scenario: Reading a directory instead of a file returns a not-a-file error
    When the supervisor reads a path that is a directory
    Then the tool returns a structured error indicating the path is not a file

  # Why: Non-UTF-8 files must be refused
  @task:TASK-J002-008
  @negative
  Scenario: Reading a file with invalid UTF-8 bytes returns an encoding error
    When the supervisor reads a file whose bytes are not valid UTF-8
    Then the tool returns a structured error indicating an encoding problem

  # Why: Missing provider key must not raise at startup
  @task:TASK-J002-009
  @negative
  Scenario: Searching the web without a configured Tavily key returns a configuration error
    Given the web-search provider is configured but no provider key is set
    When the supervisor searches the web for any query
    Then the tool returns a structured error indicating the provider key is missing
    And the supervisor continues running normally

  # Why: Empty query is invalid
  @task:TASK-J002-009
  @negative
  Scenario: Searching the web with an empty query returns an invalid-query error
    Given the web-search provider is configured with a valid key
    When the supervisor searches the web for an empty query
    Then the tool returns a structured error indicating the query must be non-empty

  # Why: Invalid window for stub calendar
  @task:TASK-J002-010
  @negative
  Scenario: Requesting calendar events for an unknown window returns an invalid-window error
    When the supervisor requests calendar events for an unsupported window value
    Then the tool returns a structured error listing the allowed windows

  # Why: Calculator must refuse unsafe tokens (no eval)
  @task:TASK-J002-011
  @negative
  Scenario Outline: Calculator rejects expressions containing unsafe tokens
    When the supervisor asks the calculator to evaluate <expression>
    Then the tool returns a structured error indicating the expression is unsafe or unparseable

    Examples:
      | expression              |
      | __import__('os').getcwd |
      | open('/etc/passwd')     |
      | lambda x: x             |

  # Why: Capability name must resolve; else structured error
  @task:TASK-J002-013
  @negative
  Scenario: Dispatching by an unknown capability name returns an unresolved error
    When the supervisor dispatches by a capability name that no registered agent advertises
    And no intent pattern is supplied
    Then the tool returns a structured error indicating the capability could not be resolved
    And the supervisor does not retry the same dispatch

  # Why: Payload must be a JSON object literal
  @task:TASK-J002-013
  @negative
  Scenario Outline: dispatch_by_capability rejects payloads that are not JSON object literals
    Given the reasoning model has identified a resolvable capability
    When the supervisor dispatches with payload_json set to <payload>
    Then the tool returns a structured error indicating the payload is not a JSON object literal

    Examples:
      | payload                 |
      | "just a string"         |
      | [1, 2, 3]               |
      | not valid json          |

  # Why: Timeout returns structured error even when the stub is configured to time out
  @task:TASK-J002-013
  @negative
  Scenario: Dispatching by capability with a simulated timeout returns a timeout error
    Given the reasoning model has identified a resolvable capability
    And the dispatch stub is configured to simulate a timeout
    When the supervisor dispatches by capability with timeout_seconds 10
    Then the tool returns a structured timeout error naming the resolved agent and the configured timeout

  # ---------------------------------------------------------------------------
  # GROUP D — Edge Cases
  # ---------------------------------------------------------------------------

  # Why: Startup-fatal misconfiguration at the stub registry path
  @task:TASK-J002-006
  @edge-case @negative
  Scenario: Starting Jarvis with a missing stub capabilities file fails fast at startup
    Given the configured stub capabilities path does not exist
    When Jarvis starts up
    Then startup fails with a file-not-found error before the supervisor is built

  # Why: Malformed YAML or invalid descriptor is startup-fatal
  @task:TASK-J002-006
  @edge-case @negative
  Scenario: Starting Jarvis with a malformed stub capabilities file fails fast at startup
    Given the configured stub capabilities file contains a descriptor with an invalid agent id
    When Jarvis starts up
    Then startup fails with a validation error before the supervisor is built

  # Why: Empty registry still renders a safe prompt block
  @task:TASK-J002-017
  @edge-case
  Scenario: Building the supervisor with no registered capabilities renders a safe prompt fallback
    When the supervisor graph is built with an empty capability list
    Then the rendered system prompt contains the text "No capabilities currently registered."

  # Why: Stubs return OK strings so reasoning model can trust them
  @task:TASK-J002-012
  @edge-case
  Scenario: capabilities_refresh and capabilities_subscribe_updates return OK acknowledgements in Phase 2
    When the supervisor calls the refresh tool
    And the supervisor calls the subscribe-updates tool
    Then each tool returns an OK acknowledgement noting that live updates arrive in Phase 3

  # Why: Intent pattern fallback when exact tool name not found
  @task:TASK-J002-013
  @edge-case
  Scenario: Dispatching by capability falls back to intent pattern matching when no exact tool match exists
    Given no registered agent advertises the requested tool name
    And at least one registered agent advertises a matching intent pattern
    When the supervisor dispatches by capability and supplies the intent pattern
    Then the tool resolves the request to the matching agent via the intent pattern
    And the returned result identifies the resolved agent

  # Why: nats-core payload shape honesty — stubbed transport, real schema
  @task:TASK-J002-013
  @edge-case
  Scenario: Stubbed dispatches construct real nats-core payloads before logging
    When the supervisor dispatches by capability via the Phase 2 stub
    Then a real CommandPayload is constructed with the expected command, args, and correlation id
    And a log line prefixed with JARVIS_DISPATCH_STUB is emitted containing the resolved agent, tool name, correlation id, and latency

  # Why: Same honesty for queue_build
  @task:TASK-J002-014
  @edge-case
  Scenario: Stubbed queue_build constructs a real BuildQueuedPayload before logging
    When the supervisor queues a valid build via the Phase 2 stub
    Then a real BuildQueuedPayload is constructed with triggered_by set to jarvis and a non-empty correlation id
    And a log line prefixed with JARVIS_QUEUE_BUILD_STUB is emitted containing the feature id, repo, and correlation id

  # Why: Tools must never raise, even on Pydantic validation failure
  @task:TASK-J002-019
  @edge-case
  Scenario Outline: Every tool converts internal errors into structured strings rather than raising
    When the supervisor invokes <tool> with input that would cause an internal error
    Then the tool returns a structured string beginning with ERROR, TIMEOUT, or DEGRADED
    And no exception propagates out of the tool boundary

    Examples:
      | tool                         |
      | read_file                    |
      | search_web                   |
      | get_calendar_events          |
      | calculate                    |
      | list_available_capabilities  |
      | dispatch_by_capability       |
      | queue_build                  |

  # ---------------------------------------------------------------------------
  # GROUP E — Security / Concurrency / Integration Edge Cases
  # ---------------------------------------------------------------------------

  # Why: Defence in depth — symlinks and null bytes are path-traversal vectors
  # [ASSUMPTION: confidence=medium] Symlinks resolving outside workspace and paths containing null bytes are rejected via the existing path-traversal error category, reusing DeepAgents built-in filesystem guards
  @task:TASK-J002-008
  @edge-case @negative
  Scenario Outline: read_file rejects paths that evade the workspace guard
    When the supervisor reads a path that is <path_kind>
    Then the tool returns a structured error indicating the path is rejected by the workspace guard

    Examples:
      | path_kind                                              |
      | a path containing a null byte                          |
      | a symlink pointing outside the workspace root          |
      | a path with ".." segments resolving outside workspace  |

  # Why: Prompt-injection payloads in search results must surface as data, not instructions
  # [ASSUMPTION: confidence=medium] search_web is a thin provider wrapper — hostile snippet text is returned verbatim and the tool itself does not perform any side-effecting action
  @task:TASK-J002-009
  @edge-case
  Scenario: search_web preserves and surfaces hostile snippet content as data without acting on it
    Given the web-search provider returns a snippet whose text attempts to instruct the reasoning model to call queue_build or dispatch_by_capability
    When the supervisor searches the web
    Then the tool returns the hostile snippet verbatim inside the WebResult payload
    And the tool does not invoke any other tool as a side effect of returning the result

  # Why: Concurrent dispatches must not share correlation state
  # [ASSUMPTION: confidence=medium] Each dispatch generates a fresh UUID4 correlation id independent of session thread, producing distinct log lines
  @task:TASK-J002-013
  @edge-case
  Scenario: Concurrent dispatch_by_capability calls produce distinct correlation ids and independent log lines
    When the supervisor issues two dispatch_by_capability calls in parallel within the same session
    Then each call is assigned a distinct correlation id
    And each call emits its own JARVIS_DISPATCH_STUB log line carrying its own correlation id

  # Why: Snapshot ordering contract matters ahead of Phase 3 live updates
  # [ASSUMPTION: confidence=low] Phase 2 refresh is a no-op so the snapshot-isolation scenario is recorded as a forward-looking invariant for Phase 3
  @task:TASK-J002-012
  @edge-case
  Scenario: list_available_capabilities returns a stable snapshot even when refresh is called concurrently
    Given the capability registry has been loaded from the stub YAML
    When the supervisor calls list_available_capabilities and capabilities_refresh in parallel
    Then list_available_capabilities returns the snapshot that was in effect when the call began
    And capabilities_refresh returns its OK acknowledgement without mutating the snapshot mid-read

  # Why: Provider unavailability must degrade, not crash
  @task:TASK-J002-009
  @edge-case @negative
  Scenario: search_web surfaces provider unavailability as a DEGRADED result
    Given the web-search provider is configured with a valid key
    And the provider returns a non-success response to the request
    When the supervisor searches the web
    Then the tool returns a structured result prefixed with DEGRADED indicating the provider is unavailable
    And the returned string includes the provider status for diagnostics

  # Why: Specialist-side failures must be reported with enough context to reason
  @task:TASK-J002-013
  @edge-case @negative
  Scenario: dispatch_by_capability surfaces specialist-side failures as structured errors
    Given the reasoning model has identified a resolvable capability
    And the dispatch stub is configured to simulate a specialist-side failure with a named reason
    When the supervisor dispatches by capability
    Then the tool returns a structured error naming the resolved agent id and the reported failure reason
