# Generated by /feature-spec
# Feature: NATS Fleet Registration and Specialist Dispatch (FEAT-JARVIS-004)
# Stack: python
# Assumptions: 12 (see feat-jarvis-004-fleet-registration-and-specialist-dispatch_assumptions.yaml)
# Generated: 2026-04-27T12:00:00Z

@feat-jarvis-004 @fleet-dispatch
Feature: NATS Fleet Registration and Specialist Dispatch
  As Jarvis
  I want to register myself on the fleet, discover specialists from the
  live catalogue, and round-trip work to them over NATS
  So that Rich can ask Jarvis to delegate to the architect, product owner,
  or any other specialist agent — with timeout, retry-with-redirect,
  trace-rich learning records, and visible degradation when the
  transport or learning substrate is unavailable

  Background:
    Given Jarvis is starting up with a configured NATS endpoint
    And the configured Graphiti endpoint
    And the configured stub capability catalogue as a fallback

  # ─── GROUP A: Key Examples ──────────────────────────────────────────────

  # Why: Symmetric fleet contract — the architectural "should" becomes runtime "does"
  @task:TASK-J004-007
  @key-example @smoke
  Scenario: Jarvis publishes its own manifest on fleet.register at startup
    Given the NATS transport is available
    When Jarvis completes startup
    Then Jarvis's manifest should be discoverable on the fleet registry
    And the manifest should identify Jarvis as a core fleet member
    And the manifest should advertise Jarvis's general-purpose-agent role
    And the manifest should advertise Jarvis's intent capabilities for conversational dispatch, capability dispatch, meta-dispatch, and memory recall

  # Why: Jarvis's continued liveness must be visible to peers
  # [ASSUMPTION: confidence=high] Heartbeat interval default 30s per API-internal §8
  @task:TASK-J004-007
  @key-example
  Scenario: Jarvis republishes its manifest periodically as a heartbeat
    Given Jarvis has registered on the fleet
    When the configured heartbeat interval elapses
    Then Jarvis's manifest should be republished to the fleet
    And the manifest's trust tier and version should remain stable across republications

  # Why: Live discovery — Phase 2's stub becomes the live catalogue
  @task:TASK-J004-014
  @key-example @smoke
  Scenario: Jarvis discovers registered specialists from the live fleet catalogue
    Given two specialist agents have registered their manifests on the fleet
    When the supervisor lists available capabilities
    Then both specialists should appear in the catalogue
    And each entry should expose the specialist's role, capabilities, and trust tier

  # Why: Phase 3 close criterion #4 — the real round-trip
  @task:TASK-J004-015
  @key-example @smoke
  Scenario: dispatch_by_capability round-trips successfully with a registered specialist
    Given a specialist is registered on the fleet that exposes a capability
    And the specialist is ready to reply to commands
    When the supervisor dispatches that capability with a valid payload
    Then the specialist should receive the command
    And the supervisor should receive the specialist's successful reply
    And the result should be returned to the reasoning model

  # Why: Live KV watch — fleet membership changes propagate without restart
  @task:TASK-J004-009
  @key-example
  Scenario: A new specialist registering mid-session becomes visible to the supervisor
    Given Jarvis has been running for some time
    And the supervisor has previously listed the fleet catalogue
    When a new specialist registers its manifest on the fleet
    Then the supervisor should see the new specialist on its next catalogue listing
    And the new specialist should be eligible for dispatch immediately

  # Why: First live ADR-FLEET-001 writes — the learning substrate lights up
  @task:TASK-J004-010
  @key-example @smoke
  Scenario: A successful dispatch writes a trace-rich record to the routing history
    Given the routing history substrate is available
    When the supervisor dispatches a capability and the specialist replies successfully
    Then a routing history record should be written for that decision
    And the record should identify the chosen specialist
    And the record should record the outcome as a first-attempt success
    And the record should include the supervisor's reasoning context, resource cost, and environmental context
    And the record should be associated with the originating session

  # ─── GROUP B: Boundary Conditions ───────────────────────────────────────

  # Why: Just-inside boundary — minimum and maximum dispatch timeout values
  # [ASSUMPTION: confidence=high] Default 60s, range 5..600 per DDR-016
  @task:TASK-J004-011
  @boundary
  Scenario Outline: Dispatch accepts timeouts within the supported range
    Given a specialist is registered for the requested capability
    When the supervisor dispatches with timeout of <timeout_seconds> seconds
    Then the dispatch should be accepted as a valid request

    Examples:
      | timeout_seconds |
      | 5               |
      | 60              |
      | 600             |

  # Why: Just-outside boundary — values below 5 or above 600 are rejected at the tool boundary
  @task:TASK-J004-011
  @boundary @negative
  Scenario Outline: Dispatch rejects timeouts outside the supported range
    Given a specialist is registered for the requested capability
    When the supervisor dispatches with timeout of <timeout_seconds> seconds
    Then the dispatch should be rejected as having an invalid timeout
    And no command should be sent to the specialist

    Examples:
      | timeout_seconds |
      | 0               |
      | 4               |
      | 601             |
      | 3600            |

  # Why: Just-inside boundary — concurrent dispatches up to the cap succeed
  # [ASSUMPTION: confidence=high] Concurrent dispatch cap default is 8 per DDR-020
  @task:TASK-J004-015
  @boundary
  Scenario: Concurrent dispatches at the cap all proceed
    Given specialists are registered and ready to reply slowly
    When the supervisor launches 8 concurrent dispatches
    Then all 8 dispatches should be accepted into flight
    And each should eventually receive its specialist's reply

  # Why: Just-outside boundary — 9th in-flight dispatch is rejected immediately as overloaded
  @task:TASK-J004-008
  @boundary @negative
  Scenario: A dispatch above the concurrent cap is rejected as overloaded
    Given 8 dispatches are already in flight
    When the supervisor attempts a 9th concurrent dispatch
    Then the supervisor should be told the dispatch system is overloaded and to retry later
    And the rejection should arrive without waiting for any in-flight dispatch to complete

  # Why: Trace records small enough to inline stay inline; nothing is offloaded unnecessarily
  # [ASSUMPTION: confidence=high] 16KB JSON-encoded filesystem-offload threshold per DDR-018
  @task:TASK-J004-010
  @boundary
  Scenario: A trace record below the offload threshold is stored inline
    Given a dispatch produces a tool-call sequence well under the offload threshold
    When the routing history record is written
    Then the tool-call sequence should be stored inline in the record
    And no trace file should be written to the local filesystem

  # Why: Trace records above the offload threshold offload to the local trace directory
  @task:TASK-J004-010
  @boundary
  Scenario: A trace record above the offload threshold is offloaded to the filesystem
    Given a dispatch produces a tool-call sequence above the offload threshold
    When the routing history record is written
    Then the tool-call sequence should be offloaded to a per-decision trace file under the local Jarvis traces directory
    And the record should reference that file by path and content hash
    And the file's content hash should match the offloaded payload

  # ─── GROUP C: Negative Cases ────────────────────────────────────────────

  # Why: Tool-boundary input contract preserved from Phase 2
  @task:TASK-J004-011
  @negative
  Scenario: Dispatch rejects a payload that is not a JSON object
    Given a specialist is registered for the requested capability
    When the supervisor dispatches with a payload that is not a JSON object literal
    Then the dispatch should be rejected as having an invalid payload
    And no command should be sent to any specialist

  # Why: Resolution failure — no descriptor matches tool_name nor intent_pattern
  @task:TASK-J004-015
  @negative
  Scenario: Dispatch returns an unresolved error when no capability matches
    Given the catalogue contains no specialist exposing the requested capability
    And no specialist matches the optional intent pattern
    When the supervisor dispatches that capability
    Then the dispatch should be reported as unresolved
    And a routing history record should be written with an unresolved outcome

  # Why: Specialist explicitly errors and no other candidate exists → specialist_error / exhausted
  @task:TASK-J004-015
  @negative
  Scenario: A single specialist replying with an error and no alternative exhausts the dispatch
    Given exactly one specialist is registered for the requested capability
    And that specialist replies with an explicit error
    When the supervisor dispatches that capability
    Then the dispatch should be reported as exhausted
    And the routing history record should capture the specialist's error reason

  # Why: Timeout with no alternative — exhausted after the bounded retry budget
  @task:TASK-J004-015
  @negative
  Scenario: A timeout with no alternative specialist exhausts the dispatch
    Given exactly one specialist is registered for the requested capability
    And that specialist does not reply within the configured timeout
    When the supervisor dispatches that capability
    Then the dispatch should be reported as a timeout that exhausted the retry budget
    And the routing history record should list the failed attempt

  # Why: NATS soft-fail at startup — chat survives, dispatch surfaces a visible degraded state
  @task:TASK-J004-016
  @negative
  Scenario: Jarvis still starts when NATS is unreachable and dispatch surfaces a degraded transport
    Given the configured NATS endpoint is unreachable
    When Jarvis completes startup
    Then Jarvis should still be available for chat
    And the supervisor should not register on the fleet
    And every dispatch attempt should be reported as transport-unavailable
    And the catalogue should fall back to the stub capability list so the reasoning model still sees a non-empty catalogue
    And the frontier escape route should remain available on attended sessions

  # Why: capabilities_refresh on the soft-fail path returns a degraded transport string
  @task:TASK-J004-016
  @negative
  Scenario: Refreshing the catalogue while NATS is unavailable reports a degraded transport
    Given Jarvis has started in NATS-unavailable mode
    When the supervisor requests a catalogue refresh
    Then the refresh should be reported as transport-unavailable
    And the catalogue should continue to serve the stub capability list

  # Why: Hard-coded plural subjects must never be emitted — singular topic convention is law
  @task:TASK-J004-019
  @negative
  Scenario: The supervisor never emits a non-canonical subject name
    Given a specialist is registered for the requested capability
    When the supervisor dispatches that capability
    Then every NATS subject the supervisor publishes to should come from the canonical singular-topic formatters
    And no plural-form subject should ever appear on the wire

  # ─── GROUP D: Edge Cases ────────────────────────────────────────────────

  # Why: The retry-with-redirect resilience case
  # [ASSUMPTION: confidence=high] Max 1 redirect; lexicographic ordering per DDR-017
  @task:TASK-J004-015
  @edge-case @smoke
  Scenario: A timeout falls back to a second specialist that succeeds
    Given two specialists are registered for the requested capability
    And the first specialist (in lexicographic order) does not reply within the timeout
    And the second specialist replies successfully
    When the supervisor dispatches that capability
    Then the supervisor should receive the second specialist's reply
    And the routing history record should record the outcome as a successful redirect
    And the record should list one prior attempt against the first specialist
    And the chosen specialist should be the second one

  # Why: Visited-set loop guard — even if both candidates time out, no third attempt is made
  @task:TASK-J004-015
  @edge-case
  Scenario: Two timeouts in a row exhaust the dispatch and never revisit the same specialist
    Given two specialists are registered for the requested capability
    And neither specialist replies within the timeout
    When the supervisor dispatches that capability
    Then the dispatch should be reported as exhausted after exactly two attempts
    And the routing history record should list both attempts in order
    And no specialist should appear more than once in the attempts list

  # Why: Specialist error also triggers retry-with-redirect
  @task:TASK-J004-015
  @edge-case
  Scenario: A specialist error falls back to a second specialist that succeeds
    Given two specialists are registered for the requested capability
    And the first specialist replies with an explicit error
    And the second specialist replies successfully
    When the supervisor dispatches that capability
    Then the supervisor should receive the second specialist's reply
    And the routing history record should capture the first specialist's error reason
    And the record's outcome should be a successful redirect

  # Why: Retry-with-redirect must NOT trigger on transport failure mid-flight
  @task:TASK-J004-016
  @edge-case
  Scenario: A NATS connection failure mid-dispatch surfaces transport-unavailable without a redirect
    Given two specialists are registered for the requested capability
    And the NATS transport fails after the first command is sent
    When the supervisor dispatches that capability
    Then the dispatch should be reported as transport-unavailable
    And the supervisor should not attempt to redirect to the second specialist
    And the routing history record should record the transport-unavailable outcome

  # Why: Graphiti soft-fail — dispatch keeps working when the learning substrate is down
  # [ASSUMPTION: confidence=high] Failure logs WARN not ERROR per DDR-019
  @task:TASK-J004-016
  @edge-case
  Scenario: Dispatches still succeed when the routing history substrate is unreachable
    Given the configured Graphiti endpoint is unreachable at startup
    When the supervisor dispatches a capability and the specialist replies successfully
    Then the dispatch should still succeed for the reasoning model
    And the routing history write should be observed to fail as a warning, not as an error
    And no routing history record should reach the substrate for that dispatch

  # Why: Trace writes are fire-and-forget — the supervisor must not pay Graphiti latency
  @task:TASK-J004-010
  @edge-case
  Scenario: A successful dispatch returns to the supervisor before its trace write completes
    Given the routing history substrate is slow to accept new records
    When the supervisor dispatches a capability and the specialist replies successfully
    Then the dispatch result should be returned to the reasoning model promptly
    And the routing history record should be written asynchronously after the dispatch returns

  # Why: Combined NATS-down + Graphiti-down — only the local-only surface remains
  @task:TASK-J004-016
  @edge-case
  Scenario: Both transport and learning substrate unavailable — Jarvis still starts
    Given the configured NATS endpoint is unreachable
    And the configured Graphiti endpoint is unreachable
    When Jarvis completes startup
    Then Jarvis should still be available for chat
    And every fleet dispatch should be reported as transport-unavailable
    And no routing history record should reach the substrate
    And local subagent dispatch and frontier escape should still work on attended sessions

  # Why: Late replies after timeout are discarded; reasoning never sees stale results
  @task:TASK-J004-015
  @edge-case
  Scenario: A specialist replying after the timeout is discarded
    Given a specialist is registered for the requested capability
    And that specialist replies after the configured timeout has elapsed
    When the supervisor dispatches that capability
    Then the supervisor should not surface the late reply to the reasoning model
    And the dispatch outcome should be a timeout, not a success

  # Why: Clean shutdown drains in-flight work and deregisters from the fleet
  # [ASSUMPTION: confidence=high] Bounded shutdown windows: 5s NATS drain, 5s routing-history flush
  @task:TASK-J004-018
  @edge-case
  Scenario: Shutdown drains in-flight dispatches and deregisters from the fleet
    Given Jarvis has been running with at least one in-flight dispatch
    When Jarvis is asked to shut down
    Then the in-flight dispatch should be allowed to complete or be drained within the bounded shutdown window
    And Jarvis should deregister itself from the fleet
    And any in-flight routing history writes should be drained within the bounded flush window

  # Why: Privacy posture — sensitive content never reaches the persisted trace
  # [ASSUMPTION: confidence=high] Redaction set includes API keys, JWTs, NATS credentials, email addresses
  @task:TASK-J004-010
  @edge-case @regression
  Scenario: Sensitive content in a trace record is redacted before persistence
    Given a dispatch's reasoning context contains a sensitive value such as a credential or API key
    When the routing history record is persisted
    Then the sensitive value should not appear in the persisted record
    And the redacted value should be replaced with a redaction marker

  # ─── GROUP E: Edge-case Expansion (security / contract / integration) ───

  # Why: Contract violation on the reply path is treated as a specialist error
  # and does NOT trigger redirect (DDR-017 explicit exclusion)
  @task:TASK-J004-019
  @edge-case @negative
  Scenario: A malformed specialist reply is treated as a specialist error without redirect
    Given two specialists are registered for the requested capability
    And the first specialist replies with content that does not match the wire contract
    When the supervisor dispatches that capability
    Then the dispatch should be reported as a specialist error
    And the supervisor should not attempt to redirect to the second specialist
    And the routing history record should record the contract-violation reason

  # Why: Snapshot isolation (ASSUM-006) — concurrent registry rebinding
  # must not corrupt an in-flight resolution
  @task:TASK-J004-009
  @edge-case
  Scenario: A specialist republishing its manifest mid-dispatch does not change the in-flight resolution
    Given a specialist is registered for the requested capability
    And the supervisor has begun resolving a dispatch against that specialist
    When the same specialist republishes a modified manifest before the reply arrives
    Then the in-flight dispatch should still target the originally resolved specialist
    And subsequent catalogue listings should reflect the new manifest

  # Why: Catalogue invalidation on deregistration must not break an in-flight call
  @task:TASK-J004-014
  @edge-case
  Scenario: A specialist deregistering mid-dispatch lets the in-flight call finish against its original target
    Given a specialist is registered for the requested capability
    And a dispatch against that specialist is in flight
    When the specialist deregisters from the fleet before its reply arrives
    Then the in-flight dispatch should still complete against the original target
    And the deregistered specialist should disappear from the next catalogue listing

  # Why: Semaphore must release on every exit path or the cap leaks
  @task:TASK-J004-017
  @edge-case @regression
  Scenario Outline: The concurrent dispatch slot is released on every dispatch outcome
    Given the dispatch system is fully saturated with one slot held by an in-flight dispatch
    When that in-flight dispatch finishes with outcome <outcome>
    Then a slot should be returned to the dispatch system
    And a subsequent dispatch should be accepted into flight

    Examples:
      | outcome                |
      | success                |
      | timeout                |
      | specialist error       |
      | transport unavailable  |
      | unresolved             |

  # Why: Audit-trail invariant — every command envelope identifies its source
  @task:TASK-J004-019
  @edge-case @regression
  Scenario: Every command envelope the supervisor emits identifies Jarvis as the source
    Given a specialist is registered for the requested capability
    When the supervisor dispatches that capability
    Then the emitted command envelope should identify Jarvis as the source agent

  # Why: Filesystem offload uniqueness — overwriting a decision file is a bug
  # [ASSUMPTION: confidence=low] Overwrite of an existing per-decision trace file
  # is treated as a write failure (logged WARN; original preserved)
  @task:TASK-J004-010
  @edge-case @negative
  Scenario: Writing a trace file that already exists for the same decision is treated as a write failure
    Given the routing history substrate is available
    And a trace file already exists at the path for a given decision id
    When the routing history writer attempts to offload another large trace at that same path
    Then the second write should be reported as a routing history write failure
    And the original trace file should remain unchanged

  # Why: Degraded specialists stay dispatch-eligible in v1; the trace records their status
  # [ASSUMPTION: confidence=medium] Manifest enum allows "degraded"; v1 lets the
  # supervisor + redirect policy handle them rather than excluding at resolution
  @task:TASK-J004-015
  @edge-case
  Scenario: A specialist reporting degraded status is still eligible for dispatch and the trace records the status
    Given a specialist is registered for the requested capability with degraded status
    When the supervisor dispatches that capability and the specialist replies successfully
    Then the supervisor should receive the specialist's reply
    And the routing history record should capture the specialist's reported status at decision time
