# Generated by /feature-spec
# Feature: Assumption Dialogue (FEAT-SPL-003, jarvis half)
# Stack: python
# Assumptions: 14 (see feat-spl-003-assumption-dialogue_assumptions.yaml)
# Generated: 2026-07-07T15:21:48Z
#
# DESIGN DECISION (settled 2026-07-07, named per WS1 build plan §5 — dated
# rationale in feat-spl-003-assumption-dialogue_summary.md §Design Decision):
# correlation_id -> Slack thread-ts mapping is the Slack-ts-in-payload
# ROUND-TRIP (parent_request_id pattern), NOT a durable KV bucket. Jarvis
# holds zero mapping state; every inbound planning notification and
# checkpoint carries its own thread anchor, projected from forge SQLite
# planning_runs.parent_request_id (the durable source of truth). Restart
# survival is therefore by construction — a validation criterion below
# (see the "after Jarvis restarts" scenarios).

@feat-spl-003 @sovereign-planning-loop @assumption-dialogue
Feature: Assumption Dialogue
  As James, an identity-pinned planning originator
  I want the factory's proposed planning assumptions delivered to my Slack
  thread as individually decidable items, and every planning update from the
  factory to reach me in that same thread
  So that a planning run's assumptions get real per-item human judgment
  (never a rubber stamp), the decisions become durable curation signal for
  the learning flywheel, and no planning message to a human ever evaporates
  unread

  Background:
    Given Jarvis is running with a connected NATS transport
    And the Slack Socket Mode connection is established
    And the planning notification consumer is running
    And Rich is configured as an authorized approval operator
    And a planning run originated by James exists with its originating Slack thread known to the factory

  # ─── GROUP A: Key Examples ──────────────────────────────────────────────

  # Why: The feature's first deliverable — today Mode P's messages to the human
  # expire unread (no consumer; JARVIS stream retains 1h/1000). This is the
  # missing return channel, gate criterion for the WS1 §5 session.
  @key-example @smoke @task:TASK-SPL003-J01
  Scenario: A planned handoff notification is rendered into the originating thread
    Given the planning run has reached its planned handoff
    When forge publishes a planning notification announcing the handoff
    Then the notification should be posted as a reply in the thread of James's original message
    And the notification should include the handoff message verbatim
    And the notification should include the correlation identifier of the planning run
    And no notification should be posted outside that thread

  # Why: The core dialogue surface — one item per assumption, forced per-item
  # decisions; the anti-rubber-stamp UX is load-bearing for WS4 preference pairs.
  @key-example @smoke @task:TASK-SPL003-J02
  Scenario: A planning checkpoint renders as a per-assumption decision prompt
    Given forge pauses the planning run at the assumption checkpoint
    When Jarvis receives the planning approval request
    Then a decision prompt should be posted in the originating thread
    And every proposed assumption should appear as its own decision item
    And each item should display the assumption text and its confidence tag
    # [ASSUMPTION: confidence=low] ASSUM-005 — the edit choice opens a prefilled input for a replacement value
    And each item should offer exactly three choices: approve, edit, and defer
    And no control should be offered that decides more than one assumption at once

  # Why: The approve disposition path — distinct per-item dispositions in the
  # published decision are the WS4 curation signal (harvest: 0 'considered').
  @key-example @smoke @task:TASK-SPL003-J03a
  Scenario: Approving every assumption publishes one decision carrying per-item dispositions
    Given a decision prompt with three proposed assumptions is displayed
    When Rich approves each assumption one by one
    # [ASSUMPTION: confidence=low] ASSUM-010 — the decision publishes when the final undecided item is decided
    Then exactly one decision should be published for the checkpoint
    # [ASSUMPTION: confidence=low] ASSUM-003 — dispositions ride the frozen approval response contract
    And the decision should record a confirmed disposition for each assumption distinctly
    And each disposition should record Rich's member id as the decider
    And the planning run should be able to proceed

  # Why: The edit disposition path — an overridden value is the highest-value
  # curation signal and the input to the forge revision cycle.
  @key-example @task:TASK-SPL003-J03b
  Scenario: Editing an assumption records an overridden disposition carrying the replacement
    Given a decision prompt with three proposed assumptions is displayed
    When Rich chooses edit on one assumption and provides a corrected value
    Then that assumption's disposition should be recorded as overridden with the corrected value
    And the dispositions of the other assumptions should be unaffected

  # Why: The defer disposition path — defer is a real disposition, not a dropped
  # signal; it drives another dialogue cycle on the forge side.
  @key-example @task:TASK-SPL003-J03a
  Scenario: Deferring an assumption records a deferred disposition and asks for another cycle
    Given a decision prompt with three proposed assumptions is displayed
    When Rich defers one assumption and approves the others
    Then that assumption's disposition should be recorded as deferred
    And the published decision should ask the planning run for another dialogue cycle
    And the other assumptions' dispositions should be preserved in the published decision

  # Why: Dialogue continuity — revision cycles stay in the one conversation the
  # originator is watching, with the cycle number visible.
  @key-example @task:TASK-SPL003-J02
  Scenario: A revision cycle re-renders in the same originating thread with its cycle number
    Given a first dialogue cycle completed with one assumption overridden
    When forge publishes the revised checkpoint for the next cycle
    Then the new decision prompt should be posted in the same originating thread
    And the prompt should show which dialogue cycle it belongs to

  # Why: The WS4 join — dispositions must be recoverable from the durable trace,
  # keyed by assumption, or preference pairs cannot be built.
  @key-example @task:TASK-SPL003-J03a
  Scenario: Per-assumption dispositions land in the planning trace record
    Given a decision prompt has been fully decided with a mix of approvals and one edit
    When the decision is published
    Then the published decision should carry every disposition keyed by its assumption identifier
    And the planning run's durable trace record should preserve each disposition distinctly

  # ─── GROUP B: Boundary Conditions ───────────────────────────────────────

  # Why: Just-inside boundaries on item count — one item and a full real-world
  # manifest must both render as individually decidable items.
  @boundary @task:TASK-SPL003-J02
  Scenario Outline: Every proposed assumption renders as its own decision item regardless of count
    Given forge pauses the planning run proposing <count> assumptions
    When Jarvis renders the decision prompt
    Then <count> decision items should be displayed
    And each item should be individually decidable

    Examples:
      | count |
      | 1     |
      | 16    |

  # Why: Just-outside boundary on message capacity — a large manifest must not
  # silently drop items when it exceeds what one message can carry.
  @boundary @task:TASK-SPL003-J02
  Scenario: A checkpoint too large for one message continues across messages in the same thread
    # [ASSUMPTION: confidence=low] ASSUM-009 — chunk size bounded by the platform's per-message block limit
    Given forge pauses the planning run proposing more assumptions than fit in a single message
    When Jarvis renders the decision prompt
    Then the decision items should continue across additional messages in the same thread
    And every assumption should remain individually decidable
    And no assumption should be dropped

  # Why: Just-inside the cycle cap — the third cycle is still a normal dialogue.
  @boundary @task:TASK-SPL003-J02
  Scenario: The third dialogue cycle still renders as a normal decision prompt
    Given two dialogue cycles have already completed for the planning run
    When forge publishes the checkpoint for the third cycle
    Then a per-assumption decision prompt should be rendered in the originating thread as usual

  # Why: Just-outside the cycle cap — cap 3 then escalate is the frozen contract;
  # the originator is never offered a fourth cycle.
  @boundary @negative @task:TASK-SPL003-J02
  Scenario: Reaching the cycle cap escalates to Rich instead of a fourth cycle
    Given three dialogue cycles have already completed for the planning run
    When the dialogue would require a fourth cycle
    Then no fourth decision prompt should be offered to the originator
    And the checkpoint should be escalated to Rich
    And the escalation should be rendered in the same originating thread addressed to Rich

  # Why: Zero-item boundary — with nothing to decide per-item, the checkpoint
  # still needs one explicit human approval, and only then.
  @boundary @task:TASK-SPL003-J02
  Scenario: A checkpoint proposing no assumptions offers a single whole-checkpoint approval
    Given forge pauses the planning run proposing no assumptions
    When Jarvis renders the decision prompt
    Then the prompt should present the checkpoint summary with a single whole-checkpoint approval
    And a whole-checkpoint approval should be offered only when there are no per-assumption items

  # ─── GROUP C: Negative Cases ────────────────────────────────────────────

  # Why: JNB-104 parity — the allowlist is the sole Slack-side authorization gate.
  @negative @task:TASK-SPL003-J03a
  Scenario: A click from outside the operator allowlist is refused
    Given a decision prompt is displayed for the planning checkpoint
    When someone outside the operator allowlist clicks approve on an assumption
    Then the click should be refused with a private notice to the clicker
    And no disposition should be recorded
    And no decision should be published

  # Why: Completeness is the anti-rubber-stamp enforcement point — no decision
  # leaves Jarvis while any item is undecided.
  @negative @task:TASK-SPL003-J03a
  Scenario: No decision is published while any assumption is undecided
    Given a decision prompt with three assumptions where only two have decisions
    When Jarvis evaluates whether the checkpoint is complete
    Then no decision should be published
    And the undecided assumption should still be awaiting its own decision

  # Why: The anti-rubber-stamp rule pinned on the rendered output itself —
  # this is what makes 'considered' curation data exist at all (WS4).
  @negative @task:TASK-SPL003-J02
  Scenario: The decision prompt never offers an approve-all control
    Given forge pauses the planning run proposing several assumptions
    When Jarvis renders the decision prompt
    Then no approve-all control should be present anywhere in the prompt
    And resolving the checkpoint should require a decision on every assumption individually

  # Why: Degraded threading must never become message loss — a thin notification
  # still reaches a human, traceably.
  @negative @task:TASK-SPL003-J01
  Scenario: A notification without a thread anchor degrades to the channel and is never dropped
    Given forge publishes a planning notification that carries no thread anchor
    When Jarvis receives the notification
    Then the notification should be posted top-level in the planning channel
    And the notification should include the correlation identifier so it can be traced by hand
    And the notification should not be dropped

  # Why: A poisoned message must not kill the return channel.
  @negative @task:TASK-SPL003-J01
  Scenario: A malformed notification is skipped and the consumer keeps running
    Given the planning notification consumer is running
    When a malformed planning notification arrives
    Then the malformed notification should be logged and skipped
    And subsequent notifications should still be rendered normally

  # Why: Propose-never-elicit is a frozen constraint (SPL scope §3.3) — the
  # dialogue renders proposals for decision; nobody gets asked open questions.
  @negative @task:TASK-SPL003-J02
  Scenario: Open questions render as decidable proposals, never as questions from Jarvis
    Given the product owner's proposals include open questions
    When Jarvis renders the decision prompt
    Then each open question should be rendered as a confidence-tagged item for decision
    And Jarvis should never pose a free-text question of its own to anyone

  # Why: JNB-105 parity for the planning surface — jarvis publishes faithfully,
  # forge is the authoritative refuser (no pending map, by design).
  @negative @regression @task:TASK-SPL003-J03a
  Scenario: A stale click after the run reached a terminal state is refused authoritatively downstream
    Given the planning run has already reached a terminal state
    When Rich clicks approve on an old decision item for that run
    Then the disposition should still be published faithfully
    And the planning run should refuse it as the single source of truth

  # ─── GROUP D: Edge Cases ────────────────────────────────────────────────

  # Why: Restart-survival of the dialogue — old buttons must keep working
  # because the dialogue state lives in the message, not in Jarvis memory.
  @edge-case @task:TASK-SPL003-J03a
  Scenario: A decision prompt rendered before a restart remains fully decidable after it
    Given a decision prompt was rendered before Jarvis last restarted
    When Rich decides the remaining assumptions after the restart
    # [ASSUMPTION: confidence=low] ASSUM-004 — dispositions are re-derived from the prompt itself on every click
    Then each decision should be captured without any re-rendering
    And the published decision should carry the dispositions of every assumption

  # Why: THE named validation criterion (WS1 §5) — the thread mapping must
  # survive a Jarvis restart; the round-trip design makes this by construction.
  @edge-case @smoke @task:TASK-SPL003-J01
  Scenario: The thread mapping survives a Jarvis restart
    Given James originated the planning run before Jarvis last restarted
    When forge publishes a planning notification for that run after the restart
    Then the notification should still be posted into the originating thread
    And the thread anchor should come from the notification itself rather than anything Jarvis remembered

  # Why: Partial dialogue state must also survive — decisions already made are
  # curation signal and must not be silently lost.
  @edge-case @task:TASK-SPL003-J03a
  Scenario: Decisions made before a restart are preserved in the final published decision
    Given two of three assumptions were decided before Jarvis restarted
    When Rich decides the third assumption after the restart
    Then the published decision should carry all three dispositions
    And the two earlier dispositions should be preserved exactly as decided

  # Why: JetStream is at-least-once — duplicate deliveries must not double-post
  # into the human's thread.
  @edge-case @task:TASK-SPL003-J01
  Scenario: A duplicate delivery of the same notification renders only once
    # [ASSUMPTION: confidence=low] ASSUM-008 — best-effort in-process dedup, matching the intake pattern
    Given the same planning notification is delivered twice in quick succession
    When Jarvis processes both deliveries
    Then the notification should be rendered in the thread only once

  # Why: Escalation continuity — the escalated prompt reaches Rich in the same
  # conversation, and forge's pinned approver stays authoritative.
  @edge-case @task:TASK-SPL003-J03a
  Scenario: An escalated checkpoint is addressed to Rich and only Rich's decision is accepted
    Given the planning checkpoint has been escalated to Rich
    When Jarvis renders the escalated decision prompt
    Then the prompt should be rendered in the originating thread mentioning Rich
    And a decision by anyone other than Rich should be refused by the planning run

  # Why: Lifecycle updates arrive in bursts around checkpoints and handoffs —
  # the return channel must keep up without losing or reordering messages.
  @edge-case @task:TASK-SPL003-J01
  Scenario: A burst of notifications for the same run all render in order
    Given forge publishes several planning notifications for the same run in quick succession
    When Jarvis renders them
    Then every notification should appear in the originating thread
    And the notifications should appear in the order they were published
