# Generated by /feature-spec
# Feature: Slack Planning Intake (FEAT-SPL-001)
# Stack: python
# Assumptions: 10 (see feat-spl-001-slack-planning-intake_assumptions.yaml)
# Generated: 2026-07-06T09:55:25Z

@feat-spl-001 @sovereign-planning-loop @slack-intake
Feature: Slack Planning Intake
  As James, an identity-pinned planning originator
  I want to post a product idea as a free-text message in the dedicated
  planning channel and have it enter the factory's planning loop as a
  durable, traceable planning request
  So that I can originate real planning work from Slack with a full audit
  trail, without anyone operating a terminal and without Jarvis doing any
  reasoning of its own — intake only

  Background:
    Given Jarvis is running with a connected NATS transport
    And the Slack Socket Mode connection is established
    And planning intake is configured with a dedicated planning channel
    And James is configured as the sole authorized planning originator

  # ─── GROUP A: Key Examples ──────────────────────────────────────────────

  # Why: The core intake path — a channel message becomes a durable planning request
  @task:TASK-SPL-J01
  @key-example @smoke
  Scenario: A planning idea posted in the channel is queued for planning
    Given James posts "Add PDF export to the reporting dashboard" in the planning channel
    When Jarvis receives the message
    Then exactly one planning request should be queued on the pipeline
    And the planning request should carry the message text verbatim
    And the planning request should pin James's Slack member id as the originating user
    And the planning request should identify Jarvis as the trigger
    And the planning request should record the slack adapter as the originating adapter
    And the planning request should be marked as a planning-stage request

  # Why: The originator must see that intake worked without leaving Slack
  @task:TASK-SPL-J01
  @key-example @smoke
  Scenario: The originator receives an in-thread acknowledgement carrying the correlation identifier
    Given James posts a planning idea in the planning channel
    When the planning request is queued
    Then an acknowledgement should be posted in the thread of the original message
    And the acknowledgement should include the correlation identifier of the planning request
    And no acknowledgement should be posted outside that thread

  # Why: DF-009 audit trail — every planning run must trace back to its originating conversation
  @task:TASK-SPL-J01
  @key-example
  Scenario: The queued planning request is traceable back to the originating Slack message
    Given James posts a planning idea in the planning channel
    When the planning request is queued
    Then the correlation identifier in the pipeline subject should equal the one inside the request
    And the planning request should reference the originating Slack message as its parent request
    And the planning request should record when the message was posted and when it was queued

  # Why: The feature's defining constraint — no reasoning in Jarvis, intake only
  @task:TASK-SPL-J01
  @key-example @smoke
  Scenario: Intake publishes the idea verbatim without any reasoning
    Given James posts a planning idea in the planning channel
    When Jarvis receives the message
    Then the planning request should be queued without invoking any reasoning model
    And the message text should not be altered, summarised, or enriched
    # [ASSUMPTION: confidence=low] target_repo is always left unset in v1; Mode P configuration supplies the default repository
    And the planning request should leave the target repository unset

  # Why: JNB-105 G2 precedent — the wire bytes must round-trip through the installed event contract
  @task:TASK-SPL-J03
  @key-example
  Scenario: The queued planning request is valid against the installed event contract
    Given James posts a planning idea in the planning channel
    When the planning request is queued
    Then the published message should round-trip through the installed planning-queued event contract
    And the reconstructed request should be recognised as a planning-queued event

  # ─── GROUP B: Boundary Conditions ───────────────────────────────────────

  # Why: Just-inside boundaries — intake must not impose its own length rules on ideas
  # [ASSUMPTION: confidence=low] No truncation is applied; Slack's own maximum message length is the only upper bound
  @task:TASK-SPL-J01
  @boundary
  Scenario Outline: Ideas of any practical length are queued verbatim
    Given James posts a planning idea of <length> in the planning channel
    When Jarvis receives the message
    Then exactly one planning request should be queued on the pipeline
    And the planning request should carry the message text verbatim

    Examples:
      | length                                  |
      | a single character                      |
      | a multi-paragraph idea of 3000 characters |
      | Slack's maximum message length          |

  # Why: Just-outside boundary — the planning contract rejects blank request text
  @task:TASK-SPL-J01
  @boundary @negative
  Scenario: A whitespace-only message is not queued
    Given James posts a message containing only whitespace in the planning channel
    When Jarvis receives the message
    Then no planning request should be queued
    And no acknowledgement should be posted
    And the discarded message should be recorded in the intake log

  # ─── GROUP C: Negative Cases ────────────────────────────────────────────

  # Why: DF-009 — planning attendance is identity-pinned; only the authorized originator may originate
  @task:TASK-SPL-J01
  @negative @smoke
  Scenario: A message from anyone other than the authorized originator is ignored
    Given a channel member other than James posts an idea in the planning channel
    When Jarvis receives the message
    Then no planning request should be queued
    # [ASSUMPTION: confidence=low] Unauthorized posts are silently ignored with a log record; no ephemeral refusal is sent
    And no reply of any kind should be posted to the channel
    And the refused message should be recorded in the intake log

  # Why: The intake surface is one dedicated channel; the bot may be present in others
  @task:TASK-SPL-J01
  @negative
  Scenario: A message in a channel other than the planning channel is ignored
    Given James posts an idea in a channel that is not the planning channel
    When Jarvis receives the message
    Then no planning request should be queued
    And no reply of any kind should be posted

  # Why: Loop prevention — the in-thread acknowledgement is itself a channel message
  @task:TASK-SPL-J01
  @negative
  Scenario: Bot-authored messages are ignored including Jarvis's own acknowledgements
    Given an acknowledgement posted by Jarvis appears in the planning channel
    When Jarvis receives the message event for it
    Then no planning request should be queued
    And no further reply should be posted

  # Why: v1 intake is top-level messages only; threads belong to the future assumption dialogue
  @task:TASK-SPL-J01
  @negative
  Scenario: A reply inside a thread is not planning intake
    Given James replies inside an existing thread in the planning channel
    When Jarvis receives the message
    Then no planning request should be queued

  # Why: Edits and deletions are notifications about old messages, not new ideas
  @task:TASK-SPL-J01
  @negative
  Scenario: Message edit and delete notifications are not planning intake
    Given James edits a previously posted idea in the planning channel
    When Jarvis receives the edit notification
    Then no planning request should be queued

  # Why: House no-op-gate convention — unconfigured features degrade to logged no-ops, never boot failures
  @task:TASK-SPL-J02
  @negative
  Scenario: Planning intake left unconfigured disables intake without affecting the rest of Jarvis
    Given no planning channel or authorized originator is configured
    When Jarvis starts
    Then Jarvis should start normally
    And planning intake should be disabled as a logged no-op
    And the approval reply path should be unaffected

  # ─── GROUP D: Edge Cases ────────────────────────────────────────────────

  # Why: The originator must learn about a failed intake without leaving Slack; never-raises discipline
  @task:TASK-SPL-J01
  @edge-case @smoke
  Scenario: A pipeline outage produces an in-thread failure notice instead of a silent loss
    Given the pipeline is unavailable
    And James posts a planning idea in the planning channel
    When Jarvis fails to queue the planning request
    Then a failure notice should be posted in the thread of the original message
    And the failure notice should invite James to repost the idea later
    And Jarvis should continue running normally

  # Why: Socket Mode redelivers unacknowledged events; a duplicate must not start two planning runs
  @task:TASK-SPL-J01
  @edge-case
  Scenario: A redelivered message event is queued exactly once
    Given James posts a planning idea in the planning channel
    And Slack delivers the same message event a second time
    When Jarvis receives both deliveries
    Then exactly one planning request should be queued on the pipeline
    And the duplicate delivery should be recorded in the intake log

  # Why: The queue is authoritative; the acknowledgement is best-effort (DDR-007 posture)
  @task:TASK-SPL-J01
  @edge-case
  Scenario: A failed acknowledgement post does not undo the queued planning request
    Given James posts a planning idea in the planning channel
    And posting to Slack is failing
    When the planning request is queued
    Then the planning request should remain queued
    And the failed acknowledgement should be recorded in the intake log
    And Jarvis should continue running normally

  # Why: JNB-104 lesson — reconnects must not duplicate listeners or publishes
  @task:TASK-SPL-J02
  @edge-case
  Scenario: Messages arriving after a Socket Mode reconnect are queued exactly once
    Given the Socket Mode connection has dropped and reconnected
    And James posts a planning idea in the planning channel
    When Jarvis receives the message
    Then exactly one planning request should be queued on the pipeline
    And exactly one acknowledgement should be posted in the thread

  # Why: Intake shares the Slack surface with the approval reply path; neither may break the other
  @task:TASK-SPL-J02
  @edge-case
  Scenario: Approval button clicks continue to work while planning intake is active
    Given planning intake is active
    And an approval request with Approve and Reject buttons is pending
    When the operator clicks Approve
    Then the approval decision should be published as before
    And no planning request should be queued for the button click
