# Generated by /feature-spec
# Feature: Async Subagent for Model Routing + Attended Frontier Escape
# Stack: python
# Assumptions: 6 (see feat-jarvis-003-async-subagent-and-frontier-escape_assumptions.yaml)
# Generated: 2026-04-24T00:00:00Z
#
# Scope reframe: the originating command named the retired four-cloud-subagent
# roster (deep_reasoner / adversarial_critic / long_research / quick_local) and
# the JA6 cloud-fallback hook. Both are superseded by ADR-ARCH-001 /
# ADR-ARCH-011 / ADR-ARCH-012 / ADR-ARCH-027 and reconciled in
# docs/design/FEAT-JARVIS-003/design.md + DDR-010 / DDR-014 / DDR-015. This
# feature file specs the authoritative design: one jarvis-reasoner AsyncSubAgent
# with a role kwarg, an attended-only escalate_to_frontier tool, and a
# swap-aware LlamaSwapAdapter with stubbed health.

@feat-jarvis-003
Feature: Async Subagent for Model Routing + Attended Frontier Escape
  As the Jarvis supervisor's reasoning model
  I want a single local jarvis-reasoner subagent that I can dispatch to with a
  named role, an attended-only escalate_to_frontier tool for cloud opinions Rich
  has explicitly asked for, and a swap-aware view of the GB10 model so my voice
  responses stay honest about latency
  So that "one reasoning model that knows which reasoning model to use" works
  in practice without ever silently sending Rich's data to a cloud provider

  Background:
    Given Jarvis has started with the FEAT-JARVIS-002 tool surface intact
    And llama-swap is reachable at the configured base URL
    And the supervisor has been built with the jarvis-reasoner async subagent wired
    And the attended tool list includes escalate_to_frontier
    And the ambient tool list excludes escalate_to_frontier

  # ---------------------------------------------------------------------------
  # GROUP A — Key Examples
  # ---------------------------------------------------------------------------

  # Why: Core path — one AsyncSubAgent named jarvis-reasoner is registered (DDR-010, ADR-ARCH-011)
  @key-example @smoke
  Scenario: A single jarvis-reasoner async subagent is registered at startup
    When the subagent registry is built from the configuration
    Then exactly one async subagent is returned
    And the subagent is named jarvis-reasoner
    And its graph identifier is jarvis_reasoner
    And its description names the local model, names the three role modes, states no cloud cost, and warns against use for arithmetic, lookups, and file reads

  # Why: Description is the contract with the reasoning model — must carry cost + latency signals
  @key-example @smoke
  Scenario: The jarvis-reasoner description carries cost and latency signals the reasoning model can read
    When the supervisor receives the subagent catalogue
    Then the description states that all inference stays on the premises
    And the description states sub-second per-turn latency when the model is loaded
    And the description warns that a cold swap can take two to four minutes and the supervisor will emit a voice acknowledgement if so

  # Why: Role-dispatch happy path for CRITIC — the canonical adversarial use-case
  @key-example @smoke
  Scenario: Dispatching to the critic role launches an async task and returns a task identifier
    Given the reasoning model wants an adversarial review of an architecture document
    When it starts an async task targeting jarvis-reasoner with role critic and a non-empty prompt
    Then the middleware returns a task identifier immediately
    And the subagent graph resolves the system prompt for the critic role
    And the task runs against the local jarvis-reasoner alias

  # Why: Role-dispatch happy path for RESEARCHER
  @key-example @smoke
  Scenario: Dispatching to the researcher role uses the open-ended research posture
    Given the reasoning model wants open-ended research on a topic
    When it starts an async task targeting jarvis-reasoner with role researcher and a non-empty prompt
    Then the middleware returns a task identifier
    And the subagent graph resolves the system prompt for the researcher role

  # Why: Role-dispatch happy path for PLANNER
  @key-example @smoke
  Scenario: Dispatching to the planner role uses the multi-step planning posture
    Given the reasoning model wants a multi-step plan
    When it starts an async task targeting jarvis-reasoner with role planner and a non-empty prompt
    Then the middleware returns a task identifier
    And the subagent graph resolves the system prompt for the planner role

  # Why: Role prompts must exist for every member of the closed RoleName enum (DDR-011)
  @key-example
  Scenario: The role prompt registry covers every member of the role enum
    When the role prompt registry is inspected
    Then it contains a non-empty system prompt for the critic role
    And it contains a non-empty system prompt for the researcher role
    And it contains a non-empty system prompt for the planner role
    And no extra members are present beyond the closed enum

  # Why: AsyncSubAgentMiddleware injects the five operational tools — supervisor sees them
  @key-example @smoke
  Scenario: Wiring the async subagent injects the five middleware operational tools
    When the supervisor is built with the jarvis-reasoner async subagent
    Then the supervisor's tool catalogue includes start_async_task, check_async_task, update_async_task, cancel_async_task, and list_async_tasks

  # Why: Attended escalation happy path — Rich asks Jarvis to ask Gemini
  @key-example @smoke
  Scenario: An attended session can escalate to the default frontier model
    Given the active session is on an attended adapter
    And the configured default frontier target is reachable
    When the reasoning model invokes escalate_to_frontier with an instruction
    Then the tool returns the frontier model's response as a string
    And the invocation is recorded as a frontier escalation event

  # Why: Supervisor prompt teaches both new sections — design.md §10
  @key-example
  Scenario: The supervisor system prompt teaches subagent routing and frontier escalation
    When the supervisor system prompt is rendered for a new session
    Then it includes a Subagent Routing section that names jarvis-reasoner and lists the three role modes
    And it includes a Frontier Escalation section that states cloud escalation is only available when Rich asks for it explicitly

  # Why: Repo-root langgraph.json declares both graphs with ASGI transport (DDR-013)
  @key-example
  Scenario: The repo-root langgraph manifest declares both graphs with ASGI transport
    When the langgraph manifest at the repo root is loaded
    Then it declares a graph named jarvis bound to the supervisor module
    And it declares a graph named jarvis_reasoner bound to the subagent module
    And both graphs use the in-process ASGI transport

  # ---------------------------------------------------------------------------
  # GROUP B — Boundary Conditions
  # ---------------------------------------------------------------------------

  # Why: Role enum is a closed set — only the three members are accepted (DDR-011)
  @boundary
  Scenario Outline: The jarvis-reasoner subagent accepts only the three documented role values
    Given the supervisor wants to dispatch to jarvis-reasoner
    When it starts an async task with role <role> and a non-empty prompt
    Then the outcome is <outcome>

    Examples:
      | role        | outcome                                                |
      | critic      | the task is launched and a task identifier is returned |
      | researcher  | the task is launched and a task identifier is returned |
      | planner     | the task is launched and a task identifier is returned |

  # Why: Just-outside boundary — anything not in the enum is rejected via structured error
  # [ASSUMPTION: confidence=low] An empty-string role value is treated as unknown_role (not missing_field);
  # RoleName("") raises at enum lookup and the subagent maps that to the unknown_role path
  @boundary @negative
  Scenario Outline: Unknown role values are rejected with a structured error
    When the supervisor starts an async task targeting jarvis-reasoner with role <role> and a non-empty prompt
    Then the subagent reports an error indicating the role was not recognised
    And the error names the three accepted role values

    Examples:
      | role           |
      | bard           |
      | adversarial    |
      | CRITIC         |
      | ""             |

  # Why: Swap ETA boundary drives ADR-ARCH-012 voice-ack policy
  @boundary
  Scenario Outline: Swap status above the voice-ack threshold triggers the supervisor TTS acknowledgement
    Given the active session is on a voice-reactive adapter
    And the llama-swap adapter reports an estimated time of <eta_seconds> seconds for the wanted alias
    When the supervisor decides whether to emit a voice acknowledgement
    Then the outcome is <outcome>

    Examples:
      | eta_seconds | outcome                                                               |
      | 0           | no voice acknowledgement is emitted; the request proceeds directly    |
      | 30          | no voice acknowledgement is emitted; the request proceeds directly    |
      | 31          | the supervisor emits the voice acknowledgement and queues the request |
      | 240         | the supervisor emits the voice acknowledgement and queues the request |

  # Why: Frontier targets are a closed set — additions require a DDR
  # [ASSUMPTION: confidence=medium] A FrontierTarget value outside the enum is rejected at
  # tool-boundary type validation before any provider is contacted
  @boundary
  Scenario Outline: Only documented frontier targets are accepted
    Given the active session is on an attended adapter
    When the reasoning model invokes escalate_to_frontier with target <target>
    Then the outcome is <outcome>

    Examples:
      | target                                 | outcome                                               |
      | GEMINI_3_1_PRO (default)               | the configured Gemini provider is invoked             |
      | OPUS_4_7                               | the configured Anthropic provider is invoked          |
      | a value not in the FrontierTarget enum | the call is rejected before any provider is contacted |

  # Why: prompt is a required, non-empty field on AsyncTaskInput
  @boundary @negative
  Scenario: An async task with an empty prompt is rejected with a missing-field error
    When the supervisor starts an async task targeting jarvis-reasoner with role critic and an empty prompt
    Then the subagent reports an error indicating the prompt field is required

  # Why: SwapStatus.eta_seconds invariant: zero means ready, negative is illegal
  @boundary
  Scenario Outline: Swap status enforces a non-negative ETA
    When the llama-swap adapter is asked to construct a swap status with eta_seconds <value>
    Then the outcome is <outcome>

    Examples:
      | value | outcome                                       |
      | 0     | a status with eta_seconds 0 is returned       |
      | 1     | a status with eta_seconds 1 is returned       |
      | -1    | construction is rejected as an invalid model  |

  # ---------------------------------------------------------------------------
  # GROUP C — Negative Cases
  # ---------------------------------------------------------------------------

  # Why: Layer 2 of DDR-014 belt+braces — executor assertion on adapter
  @negative @smoke
  Scenario: An ambient session is rejected if it somehow invokes escalate_to_frontier
    Given the active session is on an ambient adapter
    When the reasoning model invokes escalate_to_frontier with an instruction
    Then the tool returns an error indicating attended use only
    And the error names the offending adapter

  # Why: Layer 2 again — executor assertion on async-subagent caller frame
  @negative
  Scenario: A call from an async subagent frame is rejected as attended-only
    Given an async subagent invocation is in progress
    When code in that frame invokes escalate_to_frontier with an instruction
    Then the tool returns an error indicating attended use only
    And the error names the async-subagent caller frame

  # Why: Layer 3 of DDR-014 — registration absence is the third brace
  @negative @smoke
  Scenario: escalate_to_frontier is not present in the ambient tool list at all
    When the ambient tool list is assembled
    Then escalate_to_frontier is not present in the assembled list
    And the assembled list still contains all FEAT-JARVIS-002 tools

  # Why: Provider key absence — graceful structured error per ADR-ARCH-021
  @negative
  Scenario: Escalating to Gemini without a configured Google API key returns a configuration error
    Given the active session is on an attended adapter
    And no Google API key is configured
    When the reasoning model invokes escalate_to_frontier with the default target
    Then the tool returns an error indicating the Google API key is not set
    And no outbound request is made to the provider

  # Why: Provider key absence for the alternate target
  @negative
  Scenario: Escalating to Opus without a configured Anthropic API key returns a configuration error
    Given the active session is on an attended adapter
    And no Anthropic API key is configured
    When the reasoning model invokes escalate_to_frontier targeting Opus
    Then the tool returns an error indicating the Anthropic API key is not set
    And no outbound request is made to the provider

  # Why: Provider availability — degraded outcome surfaces as DEGRADED prefix
  @negative
  Scenario: Frontier provider unavailability returns a degraded result without raising
    Given the active session is on an attended adapter
    And the configured frontier provider is unreachable
    When the reasoning model invokes escalate_to_frontier with an instruction
    Then the tool returns a degraded result indicating provider unavailability
    And no exception propagates to the supervisor

  # Why: Subagent never raises — model unavailability is structured per ADR-ARCH-021
  @negative
  Scenario: A missing llama-swap alias surfaces as a structured model-unavailable error
    Given the llama-swap alias for jarvis-reasoner cannot be resolved
    When the supervisor starts an async task targeting jarvis-reasoner with role planner and a non-empty prompt
    Then the subagent reports an error indicating the model is unavailable
    And the error mentions checking the llama-swap running endpoint

  # Why: Subagent timeout is a structured TIMEOUT, not an exception
  @negative
  Scenario: An async task that exceeds its timeout returns a structured timeout result
    Given an async task targeting jarvis-reasoner is running past the configured timeout
    When the supervisor checks the task status
    Then the result indicates the task timed out
    And the result identifies the affected task

  # Why: Subagent input requires both prompt and role — missing role is rejected
  @negative
  Scenario: An async task missing the role field is rejected with a structured error
    When the supervisor starts an async task targeting jarvis-reasoner with a non-empty prompt and no role
    Then the subagent reports an error indicating a required field is missing

  # Why: Subagent factory must not silently expand its roster — guard against accidental DDR-010 regression
  @negative
  Scenario: Adding an unsanctioned subagent does not silently appear in the registry
    When the subagent registry is built from the configuration
    Then no subagent named deep_reasoner is present
    And no subagent named adversarial_critic is present
    And no subagent named long_research is present
    And no subagent named quick_local is present

  # ---------------------------------------------------------------------------
  # GROUP D — Edge Cases
  # ---------------------------------------------------------------------------

  # Why: Acceptance test for FEAT-JARVIS-003 — seven canned routing decisions
  @edge-case @smoke
  Scenario Outline: The supervisor routes the seven canned acceptance prompts to the expected tools
    Given the supervisor has been built with all FEAT-JARVIS-002 tools, the jarvis-reasoner subagent, and the attended tool list including escalate_to_frontier
    And the active session is on an attended adapter
    When the user says <prompt>
    Then the reasoning model invokes <expected_action>

    Examples:
      | prompt                                                   | expected_action                                                 |
      | "What's 15% of 847?"                                     | calculate                                                       |
      | "Summarise /tmp/test.md"                                 | read_file                                                       |
      | "Critique this architecture doc for subtle flaws."       | start_async_task targeting jarvis-reasoner with role critic     |
      | "Research Meta-Harness deeply."                          | start_async_task targeting jarvis-reasoner with role researcher |
      | "Plan the migration to Python 3.13."                     | start_async_task targeting jarvis-reasoner with role planner    |
      | "Ask Gemini 3.1 Pro for a frontier opinion on this ADR." | escalate_to_frontier with the default target                    |
      | "Build FEAT-JARVIS-EXAMPLE-001 on the jarvis repo."      | queue_build                                                     |

  # Why: Backwards-compatibility guarantee — Phase 1 + FEAT-002 callers still work
  @edge-case
  Scenario: Building the supervisor without async subagents preserves existing behaviour
    When the supervisor is built without the async-subagents argument
    Then the build succeeds
    And the supervisor's tool catalogue does not include the five middleware operational tools

  # Why: ambient_tool_factory default — design.md §8 — falls back to attended list minus frontier
  @edge-case
  Scenario: Not configuring an ambient tool factory falls back to the attended tools without frontier
    When the supervisor is built with an attended tool list and no ambient tool factory
    Then ambient and learning paths see the attended tool list with escalate_to_frontier removed

  # Why: Multiple roles in flight at once — middleware should handle parallel tasks
  @edge-case
  Scenario: Two different role-mode tasks can run in parallel without collision
    Given an async task targeting jarvis-reasoner with role critic is running
    When the supervisor starts a second async task targeting jarvis-reasoner with role planner
    Then both tasks have distinct task identifiers
    And the second task uses the planner system prompt
    And neither task overwrites the other's state

  # Why: Voice ack on cold swap — exercised on the voice-reactive adapter
  @edge-case @smoke
  Scenario: A voice-reactive session above the swap-ETA threshold receives a TTS acknowledgement and the request is queued
    Given the active session is on a voice-reactive adapter
    And the llama-swap adapter reports an estimated time of two hundred and forty seconds for jarvis-reasoner
    When the supervisor receives a request that would dispatch to jarvis-reasoner
    Then the supervisor emits the TTS acknowledgement
    And the request is queued for dispatch once the swap completes

  # Why: Swap status source defaults to stub in Phase 2 — guard against accidental live-wiring
  @edge-case
  Scenario: The llama-swap adapter reports a stub source in Phase 2
    When the llama-swap adapter is asked for the current status of any alias
    Then the returned status is marked as coming from the stub source

  # Why: Subagent graph compiles at module import — DDR-012
  @edge-case
  Scenario: Importing the jarvis-reasoner subagent module compiles its graph
    When the jarvis-reasoner subagent module is imported in a fresh process
    Then a compiled graph object is exposed at module scope
    And no LLM network call has been made

  # Why: Frontier escalation log shape feeds FEAT-JARVIS-004 trace ingestion
  @edge-case
  Scenario: A successful frontier escalation logs a structured event with target, session, correlation, adapter, instruction length, and outcome
    Given the active session is on an attended adapter with a known correlation id
    When the reasoning model successfully invokes escalate_to_frontier with an instruction
    Then a structured frontier-escalation log entry is recorded
    And the log entry contains the target, the session id, the correlation id, the adapter, the instruction length, and a success outcome
    And the log entry never contains the instruction body

  # Why: Description-text invariant guards routing-behaviour regressions
  @edge-case @regression
  Scenario: The jarvis-reasoner description does not mention the retired four-subagent roster
    When the subagent description is inspected
    Then it does not contain the names deep_reasoner, adversarial_critic, long_research, or quick_local
    And it does not promise cloud-tier reasoning

  # Why: Subagent never has further tools — leaf, per design.md §8 and DDR-010
  @edge-case
  Scenario: The jarvis-reasoner subagent graph carries no tools of its own
    When the jarvis-reasoner compiled graph is inspected
    Then it has no application tools wired
    And it has no further subagents wired

  # ---------------------------------------------------------------------------
  # GROUP E — Edge Case Expansion (Security / Concurrency / Integrity / Integration)
  # ---------------------------------------------------------------------------

  # Why: DDR-014 Layer 2 explicit spoof case — attended-session reasoning that tries to
  # call escalate_to_frontier from inside an async-subagent frame must still be rejected
  @edge-case @negative @security
  Scenario: A spoofed-ambient invocation from inside an attended session is rejected
    Given the active session is on an attended adapter
    And an async subagent invocation is in progress within that session
    When code in the async-subagent frame invokes escalate_to_frontier with an instruction
    Then the tool returns an error indicating attended use only
    And the error names the async-subagent caller frame
    And no outbound request is made to any frontier provider

  # Why: ADR-ARCH-023 — permissions are constitutional; reasoning cannot mutate them
  @edge-case @negative @security
  Scenario: The reasoning model cannot add escalate_to_frontier to the ambient tool list at runtime
    Given the supervisor has been built with attended and ambient tool lists in place
    When the reasoning model attempts to register escalate_to_frontier on the ambient tool list during a turn
    Then the ambient tool list remains unchanged
    And escalate_to_frontier is still absent from the assembled ambient list

  # Why: Layer 2 fires before the frontier model sees the instruction — prompt injection
  # in the instruction body cannot bypass the gate
  # [ASSUMPTION: confidence=medium] The attended-only error return string does not echo
  # the instruction body — consistent with ADR-ARCH-029 redaction posture applied to
  # structured error strings as well as log fields
  @edge-case @negative @security
  Scenario: A prompt-injection instruction does not bypass the attended-only gate
    Given the active session is on an ambient adapter
    When the reasoning model invokes escalate_to_frontier with an instruction that asks the gate to be ignored
    Then the tool returns an error indicating attended use only
    And no outbound request is made to any frontier provider
    And the instruction body is not echoed in the structured error

  # Why: cancel_async_task is part of the middleware contract — supervisor must be able
  # to reach a clean cancelled status without hanging
  # [ASSUMPTION: confidence=medium] A cancelled async task surfaces via check_async_task
  # with status cancelled (distinct from complete / running / error)
  @edge-case @concurrency
  Scenario: Cancelling a running jarvis-reasoner task transitions it cleanly to a cancelled status
    Given an async task targeting jarvis-reasoner with role researcher is running
    When the supervisor cancels the task by its identifier
    And the supervisor then checks the task status
    Then the result indicates the task was cancelled
    And the task identifier in the result matches the cancelled task

  # Why: Defensive — checking an unknown task identifier must not raise per ADR-ARCH-021
  # [ASSUMPTION: confidence=medium] An unknown task_id returns a structured no-such-task
  # result rather than raising or silently returning empty
  @edge-case @negative
  Scenario: Checking an unknown task identifier returns a structured no-such-task result
    When the supervisor checks the status of a task identifier that was never started
    Then the result indicates no such task exists
    And no exception propagates to the supervisor

  # Why: correlation_id is the trace-richness invariant FEAT-JARVIS-004 depends on
  @edge-case @integrity
  Scenario: The session correlation identifier propagates from input through to check-task results
    Given the active session has a known correlation identifier
    When the supervisor starts an async task targeting jarvis-reasoner with role planner, a non-empty prompt, and the session's correlation identifier
    And the supervisor later checks the task status
    Then the returned result carries the same correlation identifier the session originated with

  # Why: Empty response from the frontier provider is a degraded outcome, not silent success
  # [ASSUMPTION: confidence=medium] An empty body from the frontier provider is mapped to
  # the DEGRADED: provider_unavailable family rather than an ERROR or silent success
  @edge-case @negative @integration
  Scenario: An empty frontier response is reported as a degraded outcome
    Given the active session is on an attended adapter
    And the configured frontier provider returns an empty body
    When the reasoning model invokes escalate_to_frontier with an instruction
    Then the tool returns a degraded result indicating the provider returned no content
    And the structured frontier-escalation log entry records the degraded outcome

  # Why: Swap-adapter idempotency — repeated reads stay consistent and never accumulate state
  @edge-case @integration
  Scenario: Repeated swap-status reads for the same alias return consistent results
    Given the llama-swap adapter is configured with a stubbed status for jarvis-reasoner
    When the supervisor reads the swap status for jarvis-reasoner three times in succession
    Then each call returns an equivalent swap status
    And no internal counter or cache is mutated by the reads
