# Generated by /feature-spec
# Feature: NATS Chat Gateway (FEAT-JARVIS-006)
# Stack: python
# Assumptions: 13 (see feat-jarvis-006-nats-chat-gateway_assumptions.yaml)
# Generated: 2026-05-11T17:00:00Z

@feat-jarvis-006 @nats-chat-gateway @fleet-surface
Feature: NATS Chat Gateway
  As Rich (via the Open WebUI pipe and any other NATS-aware adapter)
  I want Jarvis to accept chat requests over the fleet bus and reply on
  the same bus, exactly as the CLI REPL accepts them over stdin today
  So that the Open WebUI pipe and any future fleet member can hold a
  conversation with the supervisor — including its dispatch and
  queue-build tool calls — without the supervisor's reasoning, session,
  or fleet-registration paths having to know which surface is talking
  to it

  Background:
    Given Jarvis has been booted with a connected NATS transport
    And Jarvis is registered on the fleet under the identifier "jarvis"
    And Jarvis's heartbeat is publishing on the fleet heartbeat subject
    And Jarvis is listening for chat requests on the jarvis command subject
    And the supervisor, session manager, and dispatch tools are wired

  # ─── GROUP A: Key Examples ──────────────────────────────────────────────

  # Why: The bootstrap criterion — the command surface exists at all
  # [ASSUMPTION: confidence=high] Implementation shape — the chat gateway ADDS only the agents.command.jarvis subscription and in-flight drain bookkeeping to the existing AppState.nats_client; it does not clone a full NATSAdapter because build_app_state already owns connect, register, heartbeat, deregister, disconnect
  # [ASSUMPTION: confidence=high] Subscription uses subscribe-with-reply on the flat subject agents.command.jarvis exactly (Bug #1 and Bug #4 must-replicate from the scope doc)
  @key-example @smoke
  Scenario: Starting the chat gateway subscribes Jarvis to the jarvis command subject
    Given Jarvis has just started in chat-gateway mode
    When the chat gateway finishes its startup sequence
    Then Jarvis should be subscribed to the jarvis command subject
    And Jarvis should be ready to receive chat requests from the fleet

  # Why: Core happy path — the OpenWebUI pipe's primary use case
  # [ASSUMPTION: confidence=high] Single command verb — the chat gateway accepts the literal command string "chat" and no other verbs
  @key-example @smoke
  Scenario: A chat request is answered by the supervisor on the reply inbox
    Given Rich sends a chat request through the fleet asking Jarvis a question
    When Jarvis receives the chat request
    Then the supervisor should be asked to answer the question
    And the supervisor's reply should be delivered on the requester's reply inbox
    And the reply should carry the supervisor's response text
    And the reply should carry the same correlation identifier as the request

  # Why: Bug #1 — observers that watch the canonical result topic must also see the answer
  # [ASSUMPTION: confidence=high] Dual-publish — every chat reply is delivered on BOTH the requester's reply inbox (raw bytes) AND the canonical result topic agents.result.jarvis (envelope-wrapped)
  @key-example @smoke
  Scenario: A chat reply is also published on the canonical Jarvis result topic
    Given Rich sends a chat request through the fleet
    When the supervisor's reply is ready
    Then a result envelope should also be published on Jarvis's canonical result topic
    And the canonical result envelope should identify Jarvis as the source
    And the canonical result envelope should carry the same correlation identifier as the request

  # Why: Proves the gateway routes through the supervisor's full tool surface, not just echo
  # [ASSUMPTION: confidence=high] Result payload shape — the reply carries the supervisor's response text, the list of tools the supervisor called, and the originating correlation identifier
  @key-example @smoke
  Scenario: A chat request that triggers a fleet dispatch returns the specialist's answer
    Given Rich sends a chat request that asks Jarvis to consult a specialist agent
    And the named specialist is available on the fleet
    When Jarvis receives the chat request
    Then the supervisor should call dispatch-by-capability against the specialist
    And the specialist's answer should be folded into the reply Rich receives
    And the reply should record that the dispatch tool was called

  # Why: Proves the gateway routes through queue-build too — closes the FEAT-005 loop over NATS
  @key-example
  Scenario: A chat request that asks Jarvis to queue a build returns the queued acknowledgement
    Given Rich sends a chat request asking Jarvis to queue a build for a planned feature
    When Jarvis receives the chat request
    Then the supervisor should call queue-build for that feature
    And the reply should tell Rich the build has been queued
    And the reply should record that the queue-build tool was called

  # Why: Multi-turn conversation — proves the gateway preserves session context across requests
  @key-example
  Scenario: A follow-up chat request on the same conversation sees the earlier turn
    Given Rich has already sent one chat request to Jarvis through the fleet
    When Rich sends a second chat request that refers back to the first
    Then the supervisor's reply should reflect the context of the earlier turn
    And both replies should be associated with the same Jarvis chat session

  # ─── GROUP B: Boundary Conditions ───────────────────────────────────────

  # Why: Just-inside drain — an in-flight chat that finishes within the drain window is delivered
  # [ASSUMPTION: confidence=high] Drain timeout is 30 seconds, matching the study-tutor NATSAdapter template
  @boundary
  Scenario: A chat reply that completes within the drain window is delivered before shutdown
    Given Rich's chat request is being answered when Jarvis is asked to shut down
    And the supervisor finishes its answer within the drain window
    When the chat gateway drains in-flight requests
    Then Rich should still receive the supervisor's reply
    And the drain should complete without warning

  # Why: Just-outside drain — an in-flight chat that overshoots the drain window does not block shutdown
  @boundary @edge-case
  Scenario: A chat reply that overshoots the drain window does not block shutdown
    Given Rich's chat request is still being answered when Jarvis is asked to shut down
    And the supervisor has not finished its answer when the drain window expires
    When the chat gateway drains in-flight requests
    Then the chat gateway should log that the drain timed out with in-flight work remaining
    And the shutdown should still proceed to deregister Jarvis from the fleet

  # Why: Just-inside Forge notification batch — pending Forge notifications ride home on the same reply
  # [ASSUMPTION: confidence=medium] Forge stage-complete notifications queued during a chat turn are appended to the same reply that closes the turn — the reply combines the supervisor's response with the pending lines (Risk #3 resolved in favour of inclusion over "ignore for demo")
  @boundary
  Scenario: Forge stage-complete notifications queued during a chat turn are included in the reply
    Given Rich's chat session has pending Forge stage-complete notifications
    When Jarvis answers Rich's next chat request
    Then the reply should include the pending Forge notification lines
    And the pending notification queue should be empty after the reply is delivered

  # Why: Just-inside conversation history — inbound history is ignored; Jarvis's session is canonical
  # [ASSUMPTION: confidence=medium] Inbound conversation_history on the request payload is ignored; the per-gateway session is the canonical history store
  @boundary
  Scenario: Inbound conversation history on the request payload is ignored
    Given Rich sends a chat request whose payload carries a conversation history block
    When Jarvis receives the chat request
    Then the supervisor should answer using only the Jarvis-side session history
    And the inbound conversation history block should not have leaked into the supervisor's prompt

  # ─── GROUP C: Negative Cases ────────────────────────────────────────────

  # Why: Single command surface — anything other than "chat" is rejected, not crashed on
  @negative
  Scenario: A request carrying an unknown command verb is refused without crashing the gateway
    Given Rich sends a request whose command verb is something other than "chat"
    When Jarvis receives the request
    Then Jarvis should reply that the command is not supported
    And the reply should indicate the request did not succeed
    And the chat gateway should remain subscribed and able to handle further requests

  # Why: Missing required argument — the gateway refuses without dropping the subscription
  @negative
  Scenario: A chat request that omits the message argument is refused
    Given Rich sends a chat request whose payload does not carry a message
    When Jarvis receives the request
    Then Jarvis should reply that the chat request was malformed
    And the reply should indicate the request did not succeed
    And the supervisor should not have been invoked

  # Why: Exception inside the supervisor turn must not crash the run-forever loop
  @negative @edge-case
  Scenario: A failure inside the supervisor turn is surfaced as a failed reply
    Given Rich sends a valid chat request
    And the supervisor raises while answering it
    When Jarvis handles the failure
    Then Rich should receive a reply indicating the chat request did not succeed
    And the reply should be delivered on both the reply inbox and the canonical result topic
    And the chat gateway should remain ready for the next chat request

  # Why: A reply attempt that fails to publish must not crash the loop or leak the request
  @negative @edge-case
  Scenario: A reply that cannot be published is logged without crashing the gateway
    Given Rich sends a valid chat request
    And the supervisor produces a reply
    But the broker rejects the reply publish
    When the chat gateway handles the publish failure
    Then the failure should be recorded against Rich's correlation identifier
    And the chat gateway should remain subscribed and able to handle further requests

  # Why: A request addressed to another agent must not be processed by Jarvis
  @negative
  Scenario: A request addressed to another agent is not handled by the Jarvis chat gateway
    Given a chat-shaped request is published for a different agent
    When the chat gateway observes the bus
    Then Jarvis should not invoke the supervisor for that request
    And Jarvis should not publish any reply on its own behalf for that request

  # ─── GROUP D: Edge Cases ────────────────────────────────────────────────

  # Why: SIGINT during a long-running chat is the most common operator action — must drain cleanly
  @edge-case @smoke
  Scenario: Interrupt-while-busy drains the in-flight chat and deregisters from the fleet
    Given Rich's chat request is being answered when the operator interrupts the chat gateway
    When the chat gateway shuts down
    Then the in-flight chat should be allowed to finish within the drain window
    And Rich should receive the supervisor's reply if it finished in time
    And the chat gateway should deregister Jarvis from the fleet before disconnecting

  # Why: Two near-simultaneous chats from the same surface must both reach the supervisor
  @edge-case
  Scenario: Two concurrent chat requests are both answered
    Given Rich sends two chat requests in close succession
    When the chat gateway receives both requests
    Then both requests should be answered by the supervisor
    And each reply should carry the correlation identifier of its own request

  # Why: Heartbeat must keep firing while serve-nats is busy answering a chat
  @edge-case
  Scenario: Heartbeat continues to fire while a chat is being answered
    Given Rich's chat request is being answered by the supervisor
    When the heartbeat interval elapses during the answer
    Then a fleet heartbeat for Jarvis should still be published on schedule

  # Why: serve-nats's entire purpose is NATS — refuse to start if the broker is unreachable
  # [ASSUMPTION: confidence=medium] When the broker is unreachable at startup, the chat gateway reports the broker is unreachable and exits non-zero rather than booting in degraded mode (chat-REPL-style soft-fail is intentionally rejected)
  @edge-case @negative
  Scenario: The chat gateway refuses to start when the NATS broker is unreachable
    Given the configured NATS broker is unreachable when Jarvis is asked to start the chat gateway
    When the chat gateway runs its startup sequence
    Then the chat gateway should report that the broker is unreachable
    And the process should exit without claiming to be ready

  # Why: A request without a reply inbox must still surface on the canonical result topic
  @edge-case
  Scenario: A chat request that carries no reply inbox still surfaces a reply on the canonical result topic
    Given Rich sends a chat request that does not carry a reply inbox
    When Jarvis answers the request
    Then a result envelope should be published on Jarvis's canonical result topic
    And the reply should not be sent on any reply inbox

  # ─── GROUP E: Phase-4 Expansion ─────────────────────────────────────────

  # ─── Security ─────────────────────────────────────────────────────────

  # Why: Source-id discipline — Jarvis must not be tricked into answering an unsigned request
  # [ASSUMPTION: confidence=medium] A request whose envelope source_id is empty or not registered on the fleet is answered with a refused reply rather than silently dropped, so the requester is told to retry from a registered surface
  @edge-case @security
  Scenario: A chat request whose envelope source_id is unrecognised is refused
    Given a chat request arrives on the Jarvis command subject
    But the request's envelope does not identify a known fleet member as its source
    When Jarvis evaluates the request
    Then Jarvis should reply that the request was not accepted
    And the reply should indicate the request did not succeed
    And the supervisor should not have been invoked

  # Why: The run-forever loop must survive an inbound payload that fails envelope decoding
  # [ASSUMPTION: confidence=medium] An inbound message whose bytes do not decode into a valid CommandPayload envelope is dropped at the gateway's parse boundary — the failure is recorded, the supervisor is never invoked, and the run-forever loop continues
  @edge-case @security
  Scenario: A chat request whose payload cannot be decoded as a command envelope is dropped without crashing the gateway
    Given a message arrives on the Jarvis command subject whose bytes are not a valid command envelope
    When the chat gateway tries to decode the message
    Then the chat gateway should record the decode failure
    And the chat gateway should not invoke the supervisor for that message
    And the chat gateway should remain subscribed and able to handle further requests

  # ─── Concurrency ──────────────────────────────────────────────────────

  # Why: Single-session-per-gateway has a real semantic cost when two requesters arrive at once
  # [ASSUMPTION: confidence=medium] In Phase 1 the gateway runs a single shared chat session; concurrent chats are serialised through that session so the supervisor never sees overlapping turns, accepting the trade-off that two unrelated requesters can observe each other's context until per-requester sessions land in a later phase
  @edge-case @concurrency
  Scenario: Two concurrent chats on the single shared session are answered one turn at a time
    Given two chat requests arrive on the Jarvis command subject before either has been answered
    When the chat gateway handles both requests
    Then the supervisor should answer them one turn at a time on the single shared session
    And each reply should carry the correlation identifier of its own request
    And the second turn should be able to see the context produced by the first turn

  # Why: Shutdown ordering — heartbeat must lose to deregister so the broker's last write is the goodbye
  @edge-case @concurrency
  Scenario: A shutdown that arrives mid-heartbeat lets the deregister be the last fleet write
    Given the heartbeat loop is about to publish a fleet heartbeat when the operator interrupts the chat gateway
    When the chat gateway shuts down
    Then the heartbeat loop should be stopped before Jarvis deregisters from the fleet
    And the deregister write should be the last fleet observation the broker records for Jarvis

  # ─── Data integrity ──────────────────────────────────────────────────

  # Why: Bug #1 under the realistic failure where the requester walked away — observers must still see the reply
  @edge-case @regression
  Scenario: A reply produced after the requester has timed out still lands on the canonical result topic
    Given Rich sends a chat request and stops waiting before the supervisor finishes
    When the supervisor's reply is finally ready
    Then a result envelope should still be published on Jarvis's canonical result topic
    And the canonical result envelope should carry the original correlation identifier
    And the chat gateway should not crash on the unread reply inbox

  # ─── Integration boundary ───────────────────────────────────────────

  # Why: Downstream specialist failures must surface to Rich through the gateway, not vanish
  @edge-case @integration
  Scenario: A chat that triggers a dispatch whose specialist times out surfaces the timeout to Rich
    Given Rich sends a chat request that asks Jarvis to consult a specialist agent
    And the named specialist does not answer within its dispatch timeout
    When Jarvis handles the dispatch timeout
    Then Rich's reply should tell him the specialist did not answer in time
    And the reply should still record that the dispatch tool was called
    And the chat gateway should remain ready for the next chat request
